name: repository_cleaner
description: A powerful and safe tool for deep repository cleanup and optimization.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  archive: ^3.3.7
  crypto: ^3.0.3
  collection: ^1.17.2
  intl: ^0.20.2

dev_dependencies:
  test: ^1.24.3
  lints: ^2.1.1
