targets:
  $default:
    builders:
      isar_generator|isar_generator:
        generate_for:
          exclude:
            - lib/src/rust/**
      json_serializable:
        generate_for:
          exclude:
            - lib/src/rust/**
      freezed:
        generate_for:
          include:
            - lib/src/rust/**
            - lib/features/**
            - lib/core/**
          exclude:
            - lib/src/rust/frb_generated*
      riverpod_generator:
        generate_for:
          exclude:
            - lib/src/rust/**
      drift_dev:
        options:
          databases:
            basir_database: lib/core/persistence/drift/basir_database.dart
          test_dir: test/drift/
          schema_dir: drift_schemas/
