#!/bin/bash

# Enhanced Debugging Tools for Baseer MVP
# المؤلف: فريق وكلاء تطوير مشروع بصير
# التاريخ: 18 ديسمبر 2025

set -e

# الألوان
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() {
    echo -e "${PURPLE}🔧 $1${NC}"
    echo "════════════════════════════════════════════════════════════════"
}

print_status() {
    echo -e "${GREEN}✅${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

print_error() {
    echo -e "${RED}❌${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ️${NC} $1"
}

print_debug() {
    echo -e "${CYAN}🐛${NC} $1"
}

# دالة عرض القائمة الرئيسية
show_main_menu() {
    clear
    echo -e "${PURPLE}🔧 Baseer MVP Debug Tools${NC}"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "1. 📊 Performance Analysis"
    echo "2. 🧪 Test Debugging"
    echo "3. 🔍 Code Analysis"
    echo "4. 📱 Device Debugging"
    echo "5. 🗄️ Database Debugging"
    echo "6. 🌐 Network Debugging"
    echo "7. 📋 System Information"
    echo "8. 🚀 Quick Fixes"
    echo "9. 📖 Debug Logs Viewer"
    echo "0. Exit"
    echo ""
    echo -n "Choose an option (0-9): "
}

# 1. Performance Analysis
performance_analysis() {
    print_header "Performance Analysis"
    
    print_info "Running Flutter performance analysis..."
    
    # تشغيل flutter analyze
    echo "🔍 Running flutter analyze..."
    if flutter analyze --no-fatal-infos > .kiro/reports/analyze_output.txt 2>&1; then
        print_status "Analysis completed"
    else
        print_warning "Analysis found issues - check .kiro/reports/analyze_output.txt"
    fi
    
    # فحص حجم التطبيق
    echo "📏 Checking app size..."
    if [ -d "build/app/outputs/flutter-apk" ]; then
        APK_SIZE=$(du -h build/app/outputs/flutter-apk/app-release.apk 2>/dev/null | cut -f1 || echo "N/A")
        print_info "APK Size: $APK_SIZE"
    else
        print_info "No release APK found - run 'flutter build apk --release' first"
    fi
    
    # فحص dependencies
    echo "📦 Analyzing dependencies..."
    flutter pub deps > .kiro/reports/dependencies_analysis.txt 2>&1
    TOTAL_DEPS=$(grep -c "^[a-zA-Z]" pubspec.yaml 2>/dev/null || echo "0")
    print_info "Total dependencies: $TOTAL_DEPS"
    
    # إنشاء تقرير الأداء
    cat > .kiro/reports/performance_debug_report.md << EOF
# Performance Debug Report

**التاريخ:** $(date '+%Y-%m-%d %H:%M:%S')

## Analysis Results
- **Flutter Analyze:** $(flutter analyze --no-fatal-infos &>/dev/null && echo "✅ Clean" || echo "⚠️ Issues found")
- **APK Size:** ${APK_SIZE:-"Not built"}
- **Dependencies:** $TOTAL_DEPS packages

## Recommendations
- Run 'flutter build apk --analyze-size' for detailed size analysis
- Use 'flutter run --profile' for performance profiling
- Check .kiro/reports/analyze_output.txt for detailed analysis

---
Generated by Debug Tools
EOF
    
    print_status "Performance analysis completed"
    print_info "Report saved to: .kiro/reports/performance_debug_report.md"
}

# 2. Test Debugging
test_debugging() {
    print_header "Test Debugging"
    
    print_info "Running comprehensive test analysis..."
    
    # تشغيل الاختبارات مع تفاصيل
    echo "🧪 Running tests with verbose output..."
    if flutter test --reporter=expanded > .kiro/reports/test_debug_output.txt 2>&1; then
        print_status "All tests passed"
    else
        print_warning "Some tests failed - check .kiro/reports/test_debug_output.txt"
    fi
    
    # حساب test coverage
    echo "📊 Calculating test coverage..."
    if flutter test --coverage > /dev/null 2>&1; then
        if [ -f "coverage/lcov.info" ]; then
            COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep "lines" | grep -o '[0-9]\+\.[0-9]\+%' || echo "N/A")
            print_info "Test coverage: $COVERAGE"
        fi
    fi
    
    # فحص ملفات الاختبار
    TOTAL_TEST_FILES=$(find test/ -name "*.dart" | wc -l 2>/dev/null || echo "0")
    UNIT_TESTS=$(find test/unit -name "*.dart" | wc -l 2>/dev/null || echo "0")
    WIDGET_TESTS=$(find test/widget -name "*.dart" | wc -l 2>/dev/null || echo "0")
    INTEGRATION_TESTS=$(find test/integration -name "*.dart" | wc -l 2>/dev/null || echo "0")
    
    print_info "Test files breakdown:"
    print_info "  - Total: $TOTAL_TEST_FILES"
    print_info "  - Unit: $UNIT_TESTS"
    print_info "  - Widget: $WIDGET_TESTS"
    print_info "  - Integration: $INTEGRATION_TESTS"
    
    print_status "Test debugging completed"
}

# 3. Code Analysis
code_analysis() {
    print_header "Code Analysis"
    
    print_info "Running comprehensive code analysis..."
    
    # فحص Dart files
    DART_FILES=$(find lib/ -name "*.dart" | wc -l 2>/dev/null || echo "0")
    TOTAL_LINES=$(find lib/ -name "*.dart" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
    
    print_info "Code statistics:"
    print_info "  - Dart files: $DART_FILES"
    print_info "  - Total lines: $TOTAL_LINES"
    
    # فحص TODO comments
    TODO_COUNT=$(grep -r "TODO" lib/ | wc -l 2>/dev/null || echo "0")
    FIXME_COUNT=$(grep -r "FIXME" lib/ | wc -l 2>/dev/null || echo "0")
    
    print_info "Code comments:"
    print_info "  - TODO items: $TODO_COUNT"
    print_info "  - FIXME items: $FIXME_COUNT"
    
    # فحص print statements
    PRINT_COUNT=$(grep -r "print(" lib/ | wc -l 2>/dev/null || echo "0")
    DEBUG_PRINT_COUNT=$(grep -r "debugPrint(" lib/ | wc -l 2>/dev/null || echo "0")
    
    print_info "Debug statements:"
    print_info "  - print(): $PRINT_COUNT"
    print_info "  - debugPrint(): $DEBUG_PRINT_COUNT"
    
    if [ "$PRINT_COUNT" -gt 0 ]; then
        print_warning "Found $PRINT_COUNT print() statements - consider using debugPrint()"
    fi
    
    print_status "Code analysis completed"
}

# 4. Device Debugging
device_debugging() {
    print_header "Device Debugging"
    
    print_info "Checking connected devices..."
    
    # فحص الأجهزة المتصلة
    flutter devices > .kiro/reports/devices_output.txt 2>&1
    DEVICE_COUNT=$(flutter devices | grep -c "•" 2>/dev/null || echo "0")
    
    print_info "Connected devices: $DEVICE_COUNT"
    
    if [ "$DEVICE_COUNT" -gt 0 ]; then
        print_status "Devices found:"
        flutter devices | grep "•" | while read line; do
            print_info "  $line"
        done
    else
        print_warning "No devices connected"
        print_info "Connect a device or start an emulator"
    fi
    
    # فحص Android SDK
    if [ -n "$ANDROID_HOME" ]; then
        print_info "Android SDK: $ANDROID_HOME"
        if command -v adb &> /dev/null; then
            ADB_DEVICES=$(adb devices | grep -c "device$" 2>/dev/null || echo "0")
            print_info "ADB devices: $ADB_DEVICES"
        fi
    else
        print_warning "ANDROID_HOME not set"
    fi
    
    print_status "Device debugging completed"
}

# 5. Database Debugging
database_debugging() {
    print_header "Database Debugging"
    
    print_info "Analyzing Isar database..."
    
    # فحص Isar models
    ISAR_MODELS=$(find lib/ -name "*_model.dart" | wc -l 2>/dev/null || echo "0")
    print_info "Isar models found: $ISAR_MODELS"
    
    # فحص database files
    if [ -d "build" ]; then
        DB_FILES=$(find build/ -name "*.isar" | wc -l 2>/dev/null || echo "0")
        print_info "Database files: $DB_FILES"
    fi
    
    # فحص collections في الكود
    COLLECTIONS=$(grep -r "@collection" lib/ | wc -l 2>/dev/null || echo "0")
    print_info "Collections defined: $COLLECTIONS"
    
    # فحص indexes
    INDEXES=$(grep -r "@Index" lib/ | wc -l 2>/dev/null || echo "0")
    print_info "Indexes defined: $INDEXES"
    
    print_status "Database debugging completed"
}

# 6. Network Debugging
network_debugging() {
    print_header "Network Debugging"
    
    print_info "Checking network configuration..."
    
    # فحص network permissions
    if [ -f "android/app/src/main/AndroidManifest.xml" ]; then
        INTERNET_PERMISSION=$(grep -c "android.permission.INTERNET" android/app/src/main/AndroidManifest.xml 2>/dev/null || echo "0")
        if [ "$INTERNET_PERMISSION" -gt 0 ]; then
            print_status "Internet permission found"
        else
            print_warning "Internet permission not found"
        fi
    fi
    
    # فحص HTTP packages
    HTTP_PACKAGES=$(grep -E "(http:|dio:|chopper:)" pubspec.yaml | wc -l 2>/dev/null || echo "0")
    print_info "HTTP packages: $HTTP_PACKAGES"
    
    # فحص network security config
    if [ -f "android/app/src/main/res/xml/network_security_config.xml" ]; then
        print_status "Network security config found"
    else
        print_info "No network security config (using defaults)"
    fi
    
    print_status "Network debugging completed"
}

# 7. System Information
system_information() {
    print_header "System Information"
    
    print_info "Gathering system information..."
    
    # Flutter information
    echo "📱 Flutter Information:"
    flutter --version | head -5
    echo ""
    
    # System information
    echo "💻 System Information:"
    print_info "OS: $(uname -s) $(uname -r)"
    print_info "Architecture: $(uname -m)"
    print_info "User: $(whoami)"
    print_info "Working Directory: $(pwd)"
    echo ""
    
    # Project information
    echo "📁 Project Information:"
    PROJECT_SIZE=$(du -sh . 2>/dev/null | cut -f1 || echo "N/A")
    print_info "Project size: $PROJECT_SIZE"
    
    if [ -f "pubspec.yaml" ]; then
        PROJECT_NAME=$(grep "name:" pubspec.yaml | cut -d' ' -f2 || echo "N/A")
        PROJECT_VERSION=$(grep "version:" pubspec.yaml | cut -d' ' -f2 || echo "N/A")
        print_info "Project name: $PROJECT_NAME"
        print_info "Project version: $PROJECT_VERSION"
    fi
    
    print_status "System information gathered"
}

# 8. Quick Fixes
quick_fixes() {
    print_header "Quick Fixes"
    
    echo "Available quick fixes:"
    echo "1. Clean and rebuild"
    echo "2. Fix formatting"
    echo "3. Update dependencies"
    echo "4. Clear caches"
    echo "5. Fix common issues"
    echo "0. Back to main menu"
    echo ""
    echo -n "Choose a fix (0-5): "
    
    read -r fix_choice
    
    case $fix_choice in
        1)
            print_info "Cleaning and rebuilding..."
            flutter clean
            flutter pub get
            flutter packages pub run build_runner build --delete-conflicting-outputs
            print_status "Clean and rebuild completed"
            ;;
        2)
            print_info "Fixing code formatting..."
            dart format lib/ test/
            print_status "Code formatting fixed"
            ;;
        3)
            print_info "Updating dependencies..."
            flutter pub upgrade
            print_status "Dependencies updated"
            ;;
        4)
            print_info "Clearing caches..."
            flutter clean
            rm -rf .dart_tool/
            rm -rf build/
            print_status "Caches cleared"
            ;;
        5)
            print_info "Fixing common issues..."
            # إصلاح مشاكل شائعة
            flutter doctor --android-licenses || true
            flutter clean
            flutter pub get
            print_status "Common issues fixed"
            ;;
        0)
            return
            ;;
        *)
            print_error "Invalid choice"
            ;;
    esac
}

# 9. Debug Logs Viewer
debug_logs_viewer() {
    print_header "Debug Logs Viewer"
    
    print_info "Available log files:"
    
    LOG_FILES=()
    if [ -d ".kiro/reports" ]; then
        while IFS= read -r -d '' file; do
            LOG_FILES+=("$file")
        done < <(find .kiro/reports -name "*.txt" -o -name "*.log" -print0 2>/dev/null)
    fi
    
    if [ ${#LOG_FILES[@]} -eq 0 ]; then
        print_warning "No log files found"
        return
    fi
    
    for i in "${!LOG_FILES[@]}"; do
        echo "$((i+1)). $(basename "${LOG_FILES[$i]}")"
    done
    echo "0. Back to main menu"
    echo ""
    echo -n "Choose a log file to view (0-${#LOG_FILES[@]}): "
    
    read -r log_choice
    
    if [ "$log_choice" -eq 0 ]; then
        return
    elif [ "$log_choice" -ge 1 ] && [ "$log_choice" -le ${#LOG_FILES[@]} ]; then
        selected_file="${LOG_FILES[$((log_choice-1))]}"
        print_info "Viewing: $(basename "$selected_file")"
        echo "════════════════════════════════════════════════════════════════"
        cat "$selected_file"
        echo "════════════════════════════════════════════════════════════════"
        echo ""
        echo "Press Enter to continue..."
        read -r
    else
        print_error "Invalid choice"
    fi
}

# إنشاء مجلد التقارير
mkdir -p .kiro/reports

# الحلقة الرئيسية
while true; do
    show_main_menu
    read -r choice
    
    case $choice in
        1) performance_analysis ;;
        2) test_debugging ;;
        3) code_analysis ;;
        4) device_debugging ;;
        5) database_debugging ;;
        6) network_debugging ;;
        7) system_information ;;
        8) quick_fixes ;;
        9) debug_logs_viewer ;;
        0) 
            print_status "Goodbye! 👋"
            exit 0
            ;;
        *)
            print_error "Invalid choice. Please try again."
            ;;
    esac
    
    echo ""
    echo "Press Enter to continue..."
    read -r
done