// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_pool`, `map_audit_record_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `try_from`

/// Initialize the native API with a database connection.
Future<void> initApi({required String databaseUrl}) =>
    RustLib.instance.api.crateApiInitApi(databaseUrl: databaseUrl);

bool checkHealth() => RustLib.instance.api.crateApiCheckHealth();

class AuditMetadataDto {
  final WhoDto who;
  final WhereDto where;
  final WhyDto why;
  final HowDto how;

  const AuditMetadataDto({
    required this.who,
    required this.where,
    required this.why,
    required this.how,
  });

  @override
  int get hashCode =>
      who.hashCode ^ where.hashCode ^ why.hashCode ^ how.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditMetadataDto &&
          runtimeType == other.runtimeType &&
          who == other.who &&
          where == other.where &&
          why == other.why &&
          how == other.how;
}

class AuditRecordDto {
  final String recordId;
  final WhoDto who;
  final WhatDto what;
  final String when;
  final WhereDto where;
  final WhyDto why;
  final HowDto how;
  final String hash;
  final String previousHash;
  final bool isVerified;

  const AuditRecordDto({
    required this.recordId,
    required this.who,
    required this.what,
    required this.when,
    required this.where,
    required this.why,
    required this.how,
    required this.hash,
    required this.previousHash,
    required this.isVerified,
  });

  @override
  int get hashCode =>
      recordId.hashCode ^
      who.hashCode ^
      what.hashCode ^
      when.hashCode ^
      where.hashCode ^
      why.hashCode ^
      how.hashCode ^
      hash.hashCode ^
      previousHash.hashCode ^
      isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditRecordDto &&
          runtimeType == other.runtimeType &&
          recordId == other.recordId &&
          who == other.who &&
          what == other.what &&
          when == other.when &&
          where == other.where &&
          why == other.why &&
          how == other.how &&
          hash == other.hash &&
          previousHash == other.previousHash &&
          isVerified == other.isVerified;
}

class HowDto {
  final String method;
  final String? procedureReference;
  final String? apiEndpoint;

  const HowDto({
    required this.method,
    this.procedureReference,
    this.apiEndpoint,
  });

  @override
  int get hashCode =>
      method.hashCode ^ procedureReference.hashCode ^ apiEndpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HowDto &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          procedureReference == other.procedureReference &&
          apiEndpoint == other.apiEndpoint;
}

class WhatDto {
  final String action;
  final String entityType;
  final String entityId;
  final String changeDescription;
  final String? oldValue;
  final String? newValue;

  const WhatDto({
    required this.action,
    required this.entityType,
    required this.entityId,
    required this.changeDescription,
    this.oldValue,
    this.newValue,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      entityType.hashCode ^
      entityId.hashCode ^
      changeDescription.hashCode ^
      oldValue.hashCode ^
      newValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhatDto &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          entityType == other.entityType &&
          entityId == other.entityId &&
          changeDescription == other.changeDescription &&
          oldValue == other.oldValue &&
          newValue == other.newValue;
}

class WhereDto {
  final String systemId;
  final String? ipAddress;
  final String? location;
  final String? deviceId;
  final String? appVersion;

  const WhereDto({
    required this.systemId,
    this.ipAddress,
    this.location,
    this.deviceId,
    this.appVersion,
  });

  @override
  int get hashCode =>
      systemId.hashCode ^
      ipAddress.hashCode ^
      location.hashCode ^
      deviceId.hashCode ^
      appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhereDto &&
          runtimeType == other.runtimeType &&
          systemId == other.systemId &&
          ipAddress == other.ipAddress &&
          location == other.location &&
          deviceId == other.deviceId &&
          appVersion == other.appVersion;
}

class WhoDto {
  final String userId;
  final String userName;
  final String role;
  final String sessionId;

  const WhoDto({
    required this.userId,
    required this.userName,
    required this.role,
    required this.sessionId,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ userName.hashCode ^ role.hashCode ^ sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhoDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userName == other.userName &&
          role == other.role &&
          sessionId == other.sessionId;
}

class WhyDto {
  final String? reasonCode;
  final String? justification;
  final String? authorizationReference;

  const WhyDto({
    this.reasonCode,
    this.justification,
    this.authorizationReference,
  });

  @override
  int get hashCode =>
      reasonCode.hashCode ^
      justification.hashCode ^
      authorizationReference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhyDto &&
          runtimeType == other.runtimeType &&
          reasonCode == other.reasonCode &&
          justification == other.justification &&
          authorizationReference == other.authorizationReference;
}
