// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/accounts.dart';
import 'api/assets.dart';
import 'api/calendar.dart';
import 'api/currency.dart';
import 'api/inventory.dart';
import 'api/ledger.dart';
import 'api/purchasing.dart';
import 'api/reports.dart';
import 'api/sales.dart';
import 'api/standards.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  AgingReportLineDto dco_decode_aging_report_line_dto(dynamic raw);

  @protected
  AssetCategoryDto dco_decode_asset_category_dto(dynamic raw);

  @protected
  AssetDto dco_decode_asset_dto(dynamic raw);

  @protected
  AuditMetadataDto dco_decode_audit_metadata_dto(dynamic raw);

  @protected
  AuditRecordDto dco_decode_audit_record_dto(dynamic raw);

  @protected
  BillPaymentDto dco_decode_bill_payment_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountDto dco_decode_box_autoadd_account_dto(dynamic raw);

  @protected
  AssetCategoryDto dco_decode_box_autoadd_asset_category_dto(dynamic raw);

  @protected
  AssetDto dco_decode_box_autoadd_asset_dto(dynamic raw);

  @protected
  AuditMetadataDto dco_decode_box_autoadd_audit_metadata_dto(dynamic raw);

  @protected
  BillPaymentDto dco_decode_box_autoadd_bill_payment_dto(dynamic raw);

  @protected
  CustomerDto dco_decode_box_autoadd_customer_dto(dynamic raw);

  @protected
  CustomerPaymentDto dco_decode_box_autoadd_customer_payment_dto(dynamic raw);

  @protected
  EntryDto dco_decode_box_autoadd_entry_dto(dynamic raw);

  @protected
  ExchangeRateDto dco_decode_box_autoadd_exchange_rate_dto(dynamic raw);

  @protected
  InventoryItemDto dco_decode_box_autoadd_inventory_item_dto(dynamic raw);

  @protected
  PeriodDto dco_decode_box_autoadd_period_dto(dynamic raw);

  @protected
  PurchaseBillDto dco_decode_box_autoadd_purchase_bill_dto(dynamic raw);

  @protected
  SalesInvoiceDto dco_decode_box_autoadd_sales_invoice_dto(dynamic raw);

  @protected
  StockMovementDto dco_decode_box_autoadd_stock_movement_dto(dynamic raw);

  @protected
  VendorDto dco_decode_box_autoadd_vendor_dto(dynamic raw);

  @protected
  CustomerDto dco_decode_customer_dto(dynamic raw);

  @protected
  CustomerPaymentDto dco_decode_customer_payment_dto(dynamic raw);

  @protected
  DrillDownEntryDto dco_decode_drill_down_entry_dto(dynamic raw);

  @protected
  EntryDto dco_decode_entry_dto(dynamic raw);

  @protected
  ExchangeRateDto dco_decode_exchange_rate_dto(dynamic raw);

  @protected
  FinancialReportDto dco_decode_financial_report_dto(dynamic raw);

  @protected
  FinancialReportLineDto dco_decode_financial_report_line_dto(dynamic raw);

  @protected
  HowDto dco_decode_how_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InventoryItemDto dco_decode_inventory_item_dto(dynamic raw);

  @protected
  InventoryValuationReportDto dco_decode_inventory_valuation_report_dto(
      dynamic raw);

  @protected
  LineDto dco_decode_line_dto(dynamic raw);

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw);

  @protected
  List<AgingReportLineDto> dco_decode_list_aging_report_line_dto(dynamic raw);

  @protected
  List<AssetCategoryDto> dco_decode_list_asset_category_dto(dynamic raw);

  @protected
  List<AssetDto> dco_decode_list_asset_dto(dynamic raw);

  @protected
  List<AuditRecordDto> dco_decode_list_audit_record_dto(dynamic raw);

  @protected
  List<CustomerDto> dco_decode_list_customer_dto(dynamic raw);

  @protected
  List<DrillDownEntryDto> dco_decode_list_drill_down_entry_dto(dynamic raw);

  @protected
  List<EntryDto> dco_decode_list_entry_dto(dynamic raw);

  @protected
  List<ExchangeRateDto> dco_decode_list_exchange_rate_dto(dynamic raw);

  @protected
  List<FinancialReportLineDto> dco_decode_list_financial_report_line_dto(
      dynamic raw);

  @protected
  List<InventoryItemDto> dco_decode_list_inventory_item_dto(dynamic raw);

  @protected
  List<LineDto> dco_decode_list_line_dto(dynamic raw);

  @protected
  List<PeriodDto> dco_decode_list_period_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PurchaseBillDto> dco_decode_list_purchase_bill_dto(dynamic raw);

  @protected
  List<SalesInvoiceDto> dco_decode_list_sales_invoice_dto(dynamic raw);

  @protected
  List<SalesInvoiceLineDto> dco_decode_list_sales_invoice_line_dto(dynamic raw);

  @protected
  List<StandardDto> dco_decode_list_standard_dto(dynamic raw);

  @protected
  List<StockMovementDto> dco_decode_list_stock_movement_dto(dynamic raw);

  @protected
  List<TrialBalanceLineDto> dco_decode_list_trial_balance_line_dto(dynamic raw);

  @protected
  List<ValuationItemDto> dco_decode_list_valuation_item_dto(dynamic raw);

  @protected
  List<VendorDto> dco_decode_list_vendor_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountDto? dco_decode_opt_box_autoadd_account_dto(dynamic raw);

  @protected
  AssetDto? dco_decode_opt_box_autoadd_asset_dto(dynamic raw);

  @protected
  ExchangeRateDto? dco_decode_opt_box_autoadd_exchange_rate_dto(dynamic raw);

  @protected
  InventoryItemDto? dco_decode_opt_box_autoadd_inventory_item_dto(dynamic raw);

  @protected
  PeriodDto? dco_decode_opt_box_autoadd_period_dto(dynamic raw);

  @protected
  PurchaseBillDto? dco_decode_opt_box_autoadd_purchase_bill_dto(dynamic raw);

  @protected
  SalesInvoiceDto? dco_decode_opt_box_autoadd_sales_invoice_dto(dynamic raw);

  @protected
  VendorDto? dco_decode_opt_box_autoadd_vendor_dto(dynamic raw);

  @protected
  PeriodDto dco_decode_period_dto(dynamic raw);

  @protected
  PurchaseBillDto dco_decode_purchase_bill_dto(dynamic raw);

  @protected
  SalesInvoiceDto dco_decode_sales_invoice_dto(dynamic raw);

  @protected
  SalesInvoiceLineDto dco_decode_sales_invoice_line_dto(dynamic raw);

  @protected
  StandardDto dco_decode_standard_dto(dynamic raw);

  @protected
  StockMovementDto dco_decode_stock_movement_dto(dynamic raw);

  @protected
  TrialBalanceDto dco_decode_trial_balance_dto(dynamic raw);

  @protected
  TrialBalanceLineDto dco_decode_trial_balance_line_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ValuationItemDto dco_decode_valuation_item_dto(dynamic raw);

  @protected
  VendorDto dco_decode_vendor_dto(dynamic raw);

  @protected
  WhatDto dco_decode_what_dto(dynamic raw);

  @protected
  WhereDto dco_decode_where_dto(dynamic raw);

  @protected
  WhoDto dco_decode_who_dto(dynamic raw);

  @protected
  WhyDto dco_decode_why_dto(dynamic raw);

  @protected
  ZakahCalendarDto dco_decode_zakah_calendar_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  AgingReportLineDto sse_decode_aging_report_line_dto(
      SseDeserializer deserializer);

  @protected
  AssetCategoryDto sse_decode_asset_category_dto(SseDeserializer deserializer);

  @protected
  AssetDto sse_decode_asset_dto(SseDeserializer deserializer);

  @protected
  AuditMetadataDto sse_decode_audit_metadata_dto(SseDeserializer deserializer);

  @protected
  AuditRecordDto sse_decode_audit_record_dto(SseDeserializer deserializer);

  @protected
  BillPaymentDto sse_decode_bill_payment_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_box_autoadd_account_dto(SseDeserializer deserializer);

  @protected
  AssetCategoryDto sse_decode_box_autoadd_asset_category_dto(
      SseDeserializer deserializer);

  @protected
  AssetDto sse_decode_box_autoadd_asset_dto(SseDeserializer deserializer);

  @protected
  AuditMetadataDto sse_decode_box_autoadd_audit_metadata_dto(
      SseDeserializer deserializer);

  @protected
  BillPaymentDto sse_decode_box_autoadd_bill_payment_dto(
      SseDeserializer deserializer);

  @protected
  CustomerDto sse_decode_box_autoadd_customer_dto(SseDeserializer deserializer);

  @protected
  CustomerPaymentDto sse_decode_box_autoadd_customer_payment_dto(
      SseDeserializer deserializer);

  @protected
  EntryDto sse_decode_box_autoadd_entry_dto(SseDeserializer deserializer);

  @protected
  ExchangeRateDto sse_decode_box_autoadd_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  InventoryItemDto sse_decode_box_autoadd_inventory_item_dto(
      SseDeserializer deserializer);

  @protected
  PeriodDto sse_decode_box_autoadd_period_dto(SseDeserializer deserializer);

  @protected
  PurchaseBillDto sse_decode_box_autoadd_purchase_bill_dto(
      SseDeserializer deserializer);

  @protected
  SalesInvoiceDto sse_decode_box_autoadd_sales_invoice_dto(
      SseDeserializer deserializer);

  @protected
  StockMovementDto sse_decode_box_autoadd_stock_movement_dto(
      SseDeserializer deserializer);

  @protected
  VendorDto sse_decode_box_autoadd_vendor_dto(SseDeserializer deserializer);

  @protected
  CustomerDto sse_decode_customer_dto(SseDeserializer deserializer);

  @protected
  CustomerPaymentDto sse_decode_customer_payment_dto(
      SseDeserializer deserializer);

  @protected
  DrillDownEntryDto sse_decode_drill_down_entry_dto(
      SseDeserializer deserializer);

  @protected
  EntryDto sse_decode_entry_dto(SseDeserializer deserializer);

  @protected
  ExchangeRateDto sse_decode_exchange_rate_dto(SseDeserializer deserializer);

  @protected
  FinancialReportDto sse_decode_financial_report_dto(
      SseDeserializer deserializer);

  @protected
  FinancialReportLineDto sse_decode_financial_report_line_dto(
      SseDeserializer deserializer);

  @protected
  HowDto sse_decode_how_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InventoryItemDto sse_decode_inventory_item_dto(SseDeserializer deserializer);

  @protected
  InventoryValuationReportDto sse_decode_inventory_valuation_report_dto(
      SseDeserializer deserializer);

  @protected
  LineDto sse_decode_line_dto(SseDeserializer deserializer);

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer);

  @protected
  List<AgingReportLineDto> sse_decode_list_aging_report_line_dto(
      SseDeserializer deserializer);

  @protected
  List<AssetCategoryDto> sse_decode_list_asset_category_dto(
      SseDeserializer deserializer);

  @protected
  List<AssetDto> sse_decode_list_asset_dto(SseDeserializer deserializer);

  @protected
  List<AuditRecordDto> sse_decode_list_audit_record_dto(
      SseDeserializer deserializer);

  @protected
  List<CustomerDto> sse_decode_list_customer_dto(SseDeserializer deserializer);

  @protected
  List<DrillDownEntryDto> sse_decode_list_drill_down_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<EntryDto> sse_decode_list_entry_dto(SseDeserializer deserializer);

  @protected
  List<ExchangeRateDto> sse_decode_list_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  List<FinancialReportLineDto> sse_decode_list_financial_report_line_dto(
      SseDeserializer deserializer);

  @protected
  List<InventoryItemDto> sse_decode_list_inventory_item_dto(
      SseDeserializer deserializer);

  @protected
  List<LineDto> sse_decode_list_line_dto(SseDeserializer deserializer);

  @protected
  List<PeriodDto> sse_decode_list_period_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PurchaseBillDto> sse_decode_list_purchase_bill_dto(
      SseDeserializer deserializer);

  @protected
  List<SalesInvoiceDto> sse_decode_list_sales_invoice_dto(
      SseDeserializer deserializer);

  @protected
  List<SalesInvoiceLineDto> sse_decode_list_sales_invoice_line_dto(
      SseDeserializer deserializer);

  @protected
  List<StandardDto> sse_decode_list_standard_dto(SseDeserializer deserializer);

  @protected
  List<StockMovementDto> sse_decode_list_stock_movement_dto(
      SseDeserializer deserializer);

  @protected
  List<TrialBalanceLineDto> sse_decode_list_trial_balance_line_dto(
      SseDeserializer deserializer);

  @protected
  List<ValuationItemDto> sse_decode_list_valuation_item_dto(
      SseDeserializer deserializer);

  @protected
  List<VendorDto> sse_decode_list_vendor_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountDto? sse_decode_opt_box_autoadd_account_dto(
      SseDeserializer deserializer);

  @protected
  AssetDto? sse_decode_opt_box_autoadd_asset_dto(SseDeserializer deserializer);

  @protected
  ExchangeRateDto? sse_decode_opt_box_autoadd_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  InventoryItemDto? sse_decode_opt_box_autoadd_inventory_item_dto(
      SseDeserializer deserializer);

  @protected
  PeriodDto? sse_decode_opt_box_autoadd_period_dto(
      SseDeserializer deserializer);

  @protected
  PurchaseBillDto? sse_decode_opt_box_autoadd_purchase_bill_dto(
      SseDeserializer deserializer);

  @protected
  SalesInvoiceDto? sse_decode_opt_box_autoadd_sales_invoice_dto(
      SseDeserializer deserializer);

  @protected
  VendorDto? sse_decode_opt_box_autoadd_vendor_dto(
      SseDeserializer deserializer);

  @protected
  PeriodDto sse_decode_period_dto(SseDeserializer deserializer);

  @protected
  PurchaseBillDto sse_decode_purchase_bill_dto(SseDeserializer deserializer);

  @protected
  SalesInvoiceDto sse_decode_sales_invoice_dto(SseDeserializer deserializer);

  @protected
  SalesInvoiceLineDto sse_decode_sales_invoice_line_dto(
      SseDeserializer deserializer);

  @protected
  StandardDto sse_decode_standard_dto(SseDeserializer deserializer);

  @protected
  StockMovementDto sse_decode_stock_movement_dto(SseDeserializer deserializer);

  @protected
  TrialBalanceDto sse_decode_trial_balance_dto(SseDeserializer deserializer);

  @protected
  TrialBalanceLineDto sse_decode_trial_balance_line_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ValuationItemDto sse_decode_valuation_item_dto(SseDeserializer deserializer);

  @protected
  VendorDto sse_decode_vendor_dto(SseDeserializer deserializer);

  @protected
  WhatDto sse_decode_what_dto(SseDeserializer deserializer);

  @protected
  WhereDto sse_decode_where_dto(SseDeserializer deserializer);

  @protected
  WhoDto sse_decode_who_dto(SseDeserializer deserializer);

  @protected
  WhyDto sse_decode_why_dto(SseDeserializer deserializer);

  @protected
  ZakahCalendarDto sse_decode_zakah_calendar_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_aging_report_line_dto(
      AgingReportLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_asset_category_dto(
      AssetCategoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_asset_dto(AssetDto self, SseSerializer serializer);

  @protected
  void sse_encode_audit_metadata_dto(
      AuditMetadataDto self, SseSerializer serializer);

  @protected
  void sse_encode_audit_record_dto(
      AuditRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_bill_payment_dto(
      BillPaymentDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_dto(
      AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_asset_category_dto(
      AssetCategoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_asset_dto(
      AssetDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audit_metadata_dto(
      AuditMetadataDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bill_payment_dto(
      BillPaymentDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_customer_dto(
      CustomerDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_customer_payment_dto(
      CustomerPaymentDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entry_dto(
      EntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_exchange_rate_dto(
      ExchangeRateDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_inventory_item_dto(
      InventoryItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_period_dto(
      PeriodDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_purchase_bill_dto(
      PurchaseBillDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sales_invoice_dto(
      SalesInvoiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stock_movement_dto(
      StockMovementDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vendor_dto(
      VendorDto self, SseSerializer serializer);

  @protected
  void sse_encode_customer_dto(CustomerDto self, SseSerializer serializer);

  @protected
  void sse_encode_customer_payment_dto(
      CustomerPaymentDto self, SseSerializer serializer);

  @protected
  void sse_encode_drill_down_entry_dto(
      DrillDownEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_entry_dto(EntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_exchange_rate_dto(
      ExchangeRateDto self, SseSerializer serializer);

  @protected
  void sse_encode_financial_report_dto(
      FinancialReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_financial_report_line_dto(
      FinancialReportLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_how_dto(HowDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_inventory_item_dto(
      InventoryItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_inventory_valuation_report_dto(
      InventoryValuationReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_line_dto(LineDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_dto(
      List<AccountDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_aging_report_line_dto(
      List<AgingReportLineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_category_dto(
      List<AssetCategoryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_dto(List<AssetDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_record_dto(
      List<AuditRecordDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_customer_dto(
      List<CustomerDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_drill_down_entry_dto(
      List<DrillDownEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entry_dto(List<EntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exchange_rate_dto(
      List<ExchangeRateDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_financial_report_line_dto(
      List<FinancialReportLineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_inventory_item_dto(
      List<InventoryItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_line_dto(List<LineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_period_dto(
      List<PeriodDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_purchase_bill_dto(
      List<PurchaseBillDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sales_invoice_dto(
      List<SalesInvoiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sales_invoice_line_dto(
      List<SalesInvoiceLineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_standard_dto(
      List<StandardDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stock_movement_dto(
      List<StockMovementDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trial_balance_line_dto(
      List<TrialBalanceLineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_valuation_item_dto(
      List<ValuationItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vendor_dto(
      List<VendorDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account_dto(
      AccountDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_asset_dto(
      AssetDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_exchange_rate_dto(
      ExchangeRateDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_inventory_item_dto(
      InventoryItemDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_period_dto(
      PeriodDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_purchase_bill_dto(
      PurchaseBillDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sales_invoice_dto(
      SalesInvoiceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_vendor_dto(
      VendorDto? self, SseSerializer serializer);

  @protected
  void sse_encode_period_dto(PeriodDto self, SseSerializer serializer);

  @protected
  void sse_encode_purchase_bill_dto(
      PurchaseBillDto self, SseSerializer serializer);

  @protected
  void sse_encode_sales_invoice_dto(
      SalesInvoiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_sales_invoice_line_dto(
      SalesInvoiceLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_standard_dto(StandardDto self, SseSerializer serializer);

  @protected
  void sse_encode_stock_movement_dto(
      StockMovementDto self, SseSerializer serializer);

  @protected
  void sse_encode_trial_balance_dto(
      TrialBalanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_trial_balance_line_dto(
      TrialBalanceLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_valuation_item_dto(
      ValuationItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_vendor_dto(VendorDto self, SseSerializer serializer);

  @protected
  void sse_encode_what_dto(WhatDto self, SseSerializer serializer);

  @protected
  void sse_encode_where_dto(WhereDto self, SseSerializer serializer);

  @protected
  void sse_encode_who_dto(WhoDto self, SseSerializer serializer);

  @protected
  void sse_encode_why_dto(WhyDto self, SseSerializer serializer);

  @protected
  void sse_encode_zakah_calendar_dto(
      ZakahCalendarDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
