import 'dart:typed_data';

import 'package:basir_accounting_system/core/providers.dart';
import 'package:basir_accounting_system/features/auth/presentation/providers/auth_provider.dart';
import 'package:crypto/crypto.dart';
import 'package:excel/excel.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// Generic data structure for tabular reports.
class ReportData {
  /// Creates report data container.
  ReportData({
    required this.title,
    required this.headers,
    required this.rows,
    this.subtitle,
    this.metadata = const {},
  });

  /// The main title of the report.
  final String title;

  /// An optional subtitle or description.
  final String? subtitle;

  /// The column headers for the report table.
  final List<String> headers;

  /// The data rows, where each row is a list of cell strings.
  final List<List<String>> rows;

  /// Additional metadata key-value pairs to include in the report.
  final Map<String, String> metadata;

  /// Generates a SHA-256 hash of the report content.
  String get contentHash {
    final content = '$title$subtitle'
        '${headers.join()}${rows.expand((r) => r).join()}';
    return sha256.convert(content.codeUnits).toString();
  }
}

/// Service for generating cryptographically signed forensic exports.
class ForensicExportService {
  /// Creates forensic export service.
  ForensicExportService(this._ref);
  final Ref _ref;

  /// Generates a PDF with a "Forensic Seal".
  Future<Uint8List> exportToPdf(ReportData data) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.cairoRegular();
    final fontBold = await PdfGoogleFonts.cairoBold();
    final user = _ref.read(basirUserProvider);
    final timestamp = DateTime.now();
    final hash = data.contentHash;

    pdf.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(
          base: font,
          bold: fontBold,
        ),
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  data.title,
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (data.subtitle != null)
                  pw.Text(
                    data.subtitle!,
                    style: const pw.TextStyle(
                      fontSize: 14,
                      color: PdfColors.grey700,
                    ),
                  ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.TableHelper.fromTextArray(
            headers: data.headers,
            data: data.rows,
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColors.blueGrey900,
            ),
            rowDecoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              ),
            ),
            cellAlignment: pw.Alignment.centerLeft,
          ),
          pw.SizedBox(height: 40),
          pw.Divider(),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Forensic Seal',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 5),
                  pw.Text('Generated by: ${user?.email ?? "System"}'),
                  pw.Text(
                    'Timestamp: '
                    '${DateFormat('yyyy-MM-dd HH:mm:ss').format(timestamp)}',
                  ),
                  pw.Text(
                    'Hash: ${hash.substring(0, 16)}...',
                    style: const pw.TextStyle(fontSize: 8),
                  ),
                ],
              ),
              pw.BarcodeWidget(
                data: hash,
                width: 60,
                height: 60,
                barcode: pw.Barcode.qrCode(),
              ),
            ],
          ),
        ],
      ),
    );

    return pdf.save();
  }

  /// Generates an Excel file with an audit trail sheet.
  Future<List<int>> exportToExcel(ReportData data) async {
    final excel = Excel.createExcel();
    final sheet = excel['Report'];
    final user = _ref.read(basirUserProvider);
    final timestamp = DateTime.now();
    final hash = data.contentHash;

    // Header
    sheet.appendRow([TextCellValue(data.title)]);
    if (data.subtitle != null) {
      sheet.appendRow([TextCellValue(data.subtitle!)]);
    }
    sheet.appendRow([]); // Spacer

    // Table Headers
    sheet.appendRow(data.headers.map(TextCellValue.new).toList());

    // Table Data
    for (final row in data.rows) {
      sheet.appendRow(row.map(TextCellValue.new).toList());
    }

    // Audit Trail Sheet
    final auditSheet = excel['Audit Trail'];
    auditSheet.appendRow([TextCellValue('Forensic Audit Trail')]);
    auditSheet.appendRow([]);
    auditSheet.appendRow([TextCellValue('Property'), TextCellValue('Value')]);
    auditSheet.appendRow([
      TextCellValue('Generated By'),
      TextCellValue(user?.email ?? 'System'),
    ]);
    auditSheet.appendRow([
      TextCellValue('Timestamp'),
      TextCellValue(timestamp.toIso8601String()),
    ]);
    auditSheet.appendRow([
      TextCellValue('Content Hash (SHA-256)'),
      TextCellValue(hash),
    ]);

    // Add Metadata
    data.metadata.forEach((key, value) {
      auditSheet.appendRow([TextCellValue(key), TextCellValue(value)]);
    });

    return excel.encode()!;
  }
}

/// مزود خدمة تصدير البيانات الجنائية
final forensicExportServiceProvider = Provider<ForensicExportService>(
  ForensicExportService.new,
);
