import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'report_export_service.g.dart';

/// خدمة تصدير التقارير العامة (PDF/CSV)
@riverpod
class ReportExportService extends _$ReportExportService {
  @override
  void build() {
    return;
  }

  /// توليد تقرير جدول PDF
  Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> data,
    String? subtitle,
  }) async {
    final doc = pw.Document();
    final font = await PdfGoogleFonts.cairoRegular();
    final fontBold = await PdfGoogleFonts.cairoBold();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(base: font, bold: fontBold),
        build: (context) => pw.Directionality(
          textDirection: pw.TextDirection.rtl,
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(title, style: const pw.TextStyle(fontSize: 24)),
                    if (subtitle != null)
                      pw.Text(
                        subtitle,
                        style: const pw.TextStyle(
                          fontSize: 14,
                          color: PdfColors.grey,
                        ),
                      ),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.TableHelper.fromTextArray(
                headers: headers,
                data: data,
                border: null,
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.grey300,
                ),
                cellHeight: 30,
                cellAlignments: {
                  for (var i = 0; i < headers.length; i++)
                    i: pw.Alignment.centerLeft,
                },
              ),
              pw.Spacer(),
              pw.Footer(
                leading: pw.Text(
                  DateTime.now().toString().split('.')[0],
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
                trailing: pw.Text(
                  'Generated by Basir',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    return doc.save();
  }

  /// مشاركة تقرير PDF
  Future<void> shareTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> data,
    String? subtitle,
    String filename = 'report.pdf',
  }) async {
    final bytes = await generateTablePdf(
      title: title,
      headers: headers,
      data: data,
      subtitle: subtitle,
    );
    await Printing.sharePdf(bytes: bytes, filename: filename);
  }

  /// توليد تقرير CSV
  String generateTableCsv({
    required List<String> headers,
    required List<List<String>> data,
  }) {
    final buffer = StringBuffer();
    // BOM for Excel compatibility with UTF-8
    buffer.write('\uFEFF');

    // Headers
    buffer.writeln(headers.map(_escapeCsv).join(','));

    // Data
    for (final row in data) {
      buffer.writeln(row.map(_escapeCsv).join(','));
    }

    return buffer.toString();
  }

  String _escapeCsv(String field) {
    if (field.contains(',') || field.contains('"') || field.contains('\n')) {
      return '"${field.replaceAll('"', '""')}"';
    }
    return field;
  }
}
