// Mocks generated by Mockito 5.4.4 from annotations
// in basir_accounting_system/test/features/expenses/presentation/screens/expenses_dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:basir_accounting_system/features/expenses/application/expense_service.dart'
    as _i4;
import 'package:basir_accounting_system/features/expenses/domain/entities/expense.dart'
    as _i2;
import 'package:basir_accounting_system/features/expenses/domain/repositories/expense_repository.dart'
    as _i3;
import 'package:decimal/decimal.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpense_0 extends _i1.SmartFake implements _i2.Expense {
  _FakeExpense_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpenseSummary_1 extends _i1.SmartFake
    implements _i3.ExpenseSummary {
  _FakeExpenseSummary_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseService extends _i1.Mock implements _i4.ExpenseService {
  @override
  _i5.Future<List<_i2.Expense>> getExpenses({
    DateTime? startDate,
    DateTime? endDate,
    String? categoryId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenses,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #categoryId: categoryId,
            #status: status,
          },
        ),
        returnValue: _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
      ) as _i5.Future<List<_i2.Expense>>);

  @override
  _i5.Future<_i2.Expense?> getExpenseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExpenseById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Expense?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Expense?>.value(),
      ) as _i5.Future<_i2.Expense?>);

  @override
  _i5.Future<_i2.Expense> createExpense({
    required String? description,
    required _i6.Decimal? amount,
    required String? currencyCode,
    required DateTime? expenseDate,
    required String? categoryId,
    String? vendorId,
    String? vendorName,
    String? receiptUrl,
    String? notes,
    bool? isRecurring = false,
    DateTime? recurringEndDate,
    String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpense,
          [],
          {
            #description: description,
            #amount: amount,
            #currencyCode: currencyCode,
            #expenseDate: expenseDate,
            #categoryId: categoryId,
            #vendorId: vendorId,
            #vendorName: vendorName,
            #receiptUrl: receiptUrl,
            #notes: notes,
            #isRecurring: isRecurring,
            #recurringEndDate: recurringEndDate,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #createExpense,
            [],
            {
              #description: description,
              #amount: amount,
              #currencyCode: currencyCode,
              #expenseDate: expenseDate,
              #categoryId: categoryId,
              #vendorId: vendorId,
              #vendorName: vendorName,
              #receiptUrl: receiptUrl,
              #notes: notes,
              #isRecurring: isRecurring,
              #recurringEndDate: recurringEndDate,
              #createdBy: createdBy,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #createExpense,
            [],
            {
              #description: description,
              #amount: amount,
              #currencyCode: currencyCode,
              #expenseDate: expenseDate,
              #categoryId: categoryId,
              #vendorId: vendorId,
              #vendorName: vendorName,
              #receiptUrl: receiptUrl,
              #notes: notes,
              #isRecurring: isRecurring,
              #recurringEndDate: recurringEndDate,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i5.Future<_i2.Expense>);

  @override
  _i5.Future<_i2.Expense> updateExpense(_i2.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [expense],
        ),
        returnValue: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #updateExpense,
            [expense],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #updateExpense,
            [expense],
          ),
        )),
      ) as _i5.Future<_i2.Expense>);

  @override
  _i5.Future<bool> deleteExpense(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Expense> approveExpense(String? id) => (super.noSuchMethod(
        Invocation.method(
          #approveExpense,
          [id],
        ),
        returnValue: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #approveExpense,
            [id],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #approveExpense,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Expense>);

  @override
  _i5.Future<_i2.Expense> rejectExpense(
    String? id, {
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectExpense,
          [id],
          {#reason: reason},
        ),
        returnValue: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #rejectExpense,
            [id],
            {#reason: reason},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #rejectExpense,
            [id],
            {#reason: reason},
          ),
        )),
      ) as _i5.Future<_i2.Expense>);

  @override
  _i5.Future<_i2.Expense> postToLedger(String? expenseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #postToLedger,
          [expenseId],
        ),
        returnValue: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #postToLedger,
            [expenseId],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Expense>.value(_FakeExpense_0(
          this,
          Invocation.method(
            #postToLedger,
            [expenseId],
          ),
        )),
      ) as _i5.Future<_i2.Expense>);

  @override
  _i5.Future<List<_i2.ExpenseCategory>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i2.ExpenseCategory>>.value(
            <_i2.ExpenseCategory>[]),
        returnValueForMissingStub: _i5.Future<List<_i2.ExpenseCategory>>.value(
            <_i2.ExpenseCategory>[]),
      ) as _i5.Future<List<_i2.ExpenseCategory>>);

  @override
  _i5.Future<_i3.ExpenseSummary> getExpenseSummary({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenseSummary,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<_i3.ExpenseSummary>.value(_FakeExpenseSummary_1(
          this,
          Invocation.method(
            #getExpenseSummary,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.ExpenseSummary>.value(_FakeExpenseSummary_1(
          this,
          Invocation.method(
            #getExpenseSummary,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<_i3.ExpenseSummary>);

  @override
  _i5.Future<Map<String, double>> getExpensesByCategories({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpensesByCategories,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i2.Expense>> getCurrentMonthExpenses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthExpenses,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
      ) as _i5.Future<List<_i2.Expense>>);

  @override
  _i5.Future<List<_i2.Expense>> getCurrentYearExpenses() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentYearExpenses,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
      ) as _i5.Future<List<_i2.Expense>>);
}
