// Mocks generated by Mockito 5.4.4 from annotations
// in basir_accounting_system/test/features/invoices/data/repositories/invoice_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:basir_accounting_system/features/invoices/data/datasources/invoice_local_data_source.dart'
    as _i2;
import 'package:basir_accounting_system/features/invoices/domain/entities/invoice.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: invalid_use_of_visible_for_overriding_member
// ignore_for_file: invalid_visibilities_for_template_type_arguments
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: null_check_on_nullable_type_parameter
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInvoice_0 extends _i1.SmartFake implements _i4.Invoice {
  _FakeInvoice_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [InvoiceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceLocalDataSource extends _i1.Mock
    implements _i2.InvoiceLocalDataSource {
  MockInvoiceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Invoice>> getInvoices() => (super.noSuchMethod(
        Invocation.method(#getInvoices, []),
        returnValue: _i3.Future<List<_i4.Invoice>>.value(<_i4.Invoice>[]),
      ) as _i3.Future<List<_i4.Invoice>>);

  @override
  _i3.Future<_i4.Invoice> getInvoice(String? id) => (super.noSuchMethod(
        Invocation.method(#getInvoice, [id]),
        returnValue: _i3.Future<_i4.Invoice>.value(
          _FakeInvoice_0(this, Invocation.method(#getInvoice, [id])),
        ),
      ) as _i3.Future<_i4.Invoice>);

  @override
  _i3.Future<void> cacheInvoice(_i4.Invoice? invoice) => (super.noSuchMethod(
        Invocation.method(#cacheInvoice, [invoice]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheInvoices(List<_i4.Invoice>? invoices) =>
      (super.noSuchMethod(
        Invocation.method(#cacheInvoices, [invoices]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteInvoice(String? id) => (super.noSuchMethod(
        Invocation.method(#deleteInvoice, [id]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateInvoice(_i4.Invoice? invoice) => (super.noSuchMethod(
        Invocation.method(#updateInvoice, [invoice]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
