allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

apply from: "isar_flutter_libs_fix.gradle"

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
