#!/bin/bash

# Enhanced Documentation Generator v2.0
# Implements: COLLABORATION FIRST, KISS, Security First, Quality First, ENGLISH FOR CODE
# Project: basir_accounting_system
# Author: Basir Accounting System Development Agents Team
# Date: January 11, 2026

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOCS_DIR="docs/api"
HTML_DIR="$DOCS_DIR/html"
PDF_FILE="$DOCS_DIR/api-documentation.pdf"

# Print colored message
print_message() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

# Print section header
print_header() {
    echo ""
    print_message "$BLUE" "=================================================="
    print_message "$BLUE" "$1"
    print_message "$BLUE" "=================================================="
    echo ""
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Pre-generation checks
pre_generation_checks() {
    print_header "🔍 Pre-Generation Checks"
    
    # Check Flutter
    if ! command_exists flutter; then
        print_message "$RED" "❌ Flutter not found. Please install Flutter SDK."
        exit 1
    fi
    print_message "$GREEN" "✅ Flutter found: $(flutter --version | head -n 1)"
    
    # Check Dart
    if ! command_exists dart; then
        print_message "$RED" "❌ Dart not found"
        exit 1
    fi
    print_message "$GREEN" "✅ Dart found: $(dart --version 2>&1 | head -n 1)"
    
    # Check if lib directory exists
    if [ ! -d "lib" ]; then
        print_message "$RED" "❌ lib directory not found. Are you in the project root?"
        exit 1
    fi
    print_message "$GREEN" "✅ lib directory found"
}

# Generate DartDoc
generate_dartdoc() {
    print_header "📚 Generating DartDoc"
    
    print_message "$BLUE" "Generating API documentation..."
    
    # Clean previous docs
    if [ -d "$DOCS_DIR" ]; then
        print_message "$BLUE" "🧹 Cleaning previous documentation..."
        rm -rf "$DOCS_DIR"
    fi
    
    # Generate documentation
    if ! dart doc --output "$HTML_DIR"; then
        print_message "$RED" "❌ Documentation generation failed"
        exit 1
    fi
    
    print_message "$GREEN" "✅ DartDoc generated successfully"
}

# Enhance HTML documentation
enhance_html() {
    print_header "✨ Enhancing HTML Documentation"
    
    if [ ! -d "$HTML_DIR" ]; then
        print_message "$YELLOW" "⚠️  HTML directory not found. Skipping enhancement..."
        return
    fi
    
    # Add custom CSS for better styling
    print_message "$BLUE" "Adding custom styling..."
    
    cat > "$HTML_DIR/custom.css" << 'EOF'
/* Custom basir_accounting_system Documentation Styles */
:root {
    --primary-color: #2196F3;
    --secondary-color: #4CAF50;
    --text-color: #333;
    --bg-color: #f5f5f5;
}

body {
    font-family: 'Cairo', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: var(--bg-color);
}

.sidebar {
    background-color: white;
    box-shadow: 2px 0 5px rgba(0,0,0,0.1);
}

h1, h2, h3 {
    color: var(--primary-color);
}

.signature {
    background-color: #f8f9fa;
    border-left: 3px solid var(--primary-color);
    padding: 10px;
    margin: 10px 0;
}

code {
    background-color: #f4f4f4;
    padding: 2px 6px;
    border-radius: 3px;
}

.footer {
    text-align: center;
    padding: 20px;
    color: #666;
    border-top: 1px solid #ddd;
}
EOF
    
    # Add footer to index.html
    if [ -f "$HTML_DIR/index.html" ]; then
        print_message "$BLUE" "Adding project footer..."
        
        # Add custom CSS link and footer
        sed -i 's|</head>|<link rel="stylesheet" href="custom.css">\n</head>|' "$HTML_DIR/index.html"
        sed -i 's|</body>|<div class="footer">Generated by Basir Development Agents Team | $(date +%Y-%m-%d)</div>\n</body>|' "$HTML_DIR/index.html"
    fi
    
    print_message "$GREEN" "✅ HTML documentation enhanced"
}

# Generate PDF (requires wkhtmltopdf)
generate_pdf() {
    print_header "📄 Generating PDF Documentation"
    
    if ! command_exists wkhtmltopdf; then
        print_message "$YELLOW" "⚠️  wkhtmltopdf not found. Skipping PDF generation..."
        print_message "$YELLOW" "💡 Install with:"
        print_message "$YELLOW" "   - Linux: sudo apt-get install wkhtmltopdf"
        print_message "$YELLOW" "   - macOS: brew install wkhtmltopdf"
        return
    fi
    
    if [ ! -f "$HTML_DIR/index.html" ]; then
        print_message "$YELLOW" "⚠️  HTML documentation not found. Skipping PDF generation..."
        return
    fi
    
    print_message "$BLUE" "Converting HTML to PDF..."
    
    mkdir -p "$(dirname "$PDF_FILE")"
    
    if wkhtmltopdf \
        --enable-local-file-access \
        --page-size A4 \
        --margin-top 20mm \
        --margin-bottom 20mm \
        --margin-left 15mm \
        --margin-right 15mm \
        "$HTML_DIR/index.html" \
        "$PDF_FILE" 2>/dev/null; then
        
        local pdf_size_kb=$(du -k "$PDF_FILE" | cut -f1)
        print_message "$GREEN" "✅ PDF generated: $PDF_FILE (${pdf_size_kb}KB)"
    else
        print_message "$YELLOW" "⚠️  PDF generation failed"
    fi
}

# Deploy to GitHub Pages (optional)
deploy_to_github_pages() {
    print_header "🚀 Deploy to GitHub Pages"
    
    print_message "$BLUE" "Do you want to deploy to GitHub Pages? (y/n)"
    read -p "> " -n 1 -r
    echo ""
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_message "$YELLOW" "Skipping GitHub Pages deployment"
        return
    fi
    
    if [ ! -d "$HTML_DIR" ]; then
        print_message "$RED" "❌ HTML documentation not found"
        return
    fi
    
    # Check if gh-pages branch exists
    if ! git rev-parse --verify gh-pages >/dev/null 2>&1; then
        print_message "$BLUE" "Creating gh-pages branch..."
        git checkout --orphan gh-pages
        git rm -rf .
        git commit --allow-empty -m "Initial gh-pages commit"
        git checkout main
    fi
    
    print_message "$BLUE" "Deploying to gh-pages branch..."
    
    # Copy docs to temporary location
    temp_docs=$(mktemp -d)
    cp -r "$HTML_DIR"/* "$temp_docs/"
    
    # Switch to gh-pages and update
    git checkout gh-pages
    rm -rf *
    cp -r "$temp_docs"/* .
    rm -rf "$temp_docs"
    
    # Commit and push
    git add .
    git commit -m "docs: update API documentation $(date +%Y-%m-%d)"
    git push origin gh-pages
    
    # Switch back to main
    git checkout main
    
    print_message "$GREEN" "✅ Documentation deployed to GitHub Pages"
    print_message "$BLUE" "📖 View at: https://YOUR_USERNAME.github.io/YOUR_REPO/"
}

# Generate coverage report
generate_coverage_docs() {
    print_header "📊 Generating Coverage Documentation"
    
    if [ ! -f "coverage/lcov.info" ]; then
        print_message "$YELLOW" "⚠️  Coverage data not found. Running tests..."
        flutter test --coverage
    fi
    
    if command_exists genhtml; then
        print_message "$BLUE" "Generating coverage HTML report..."
        
        genhtml coverage/lcov.info \
            -o "$DOCS_DIR/coverage" \
            --title "basir_accounting_system - Test Coverage" \
            --legend
        
        print_message "$GREEN" "✅ Coverage report generated: $DOCS_DIR/coverage/index.html"
    else
        print_message "$YELLOW" "⚠️  genhtml not found. Skipping coverage HTML generation..."
        print_message "$YELLOW" "💡 Install with: apt-get install lcov (Linux) or brew install lcov (macOS)"
    fi
}

# Generate documentation index
generate_index() {
    print_header "📑 Generating Documentation Index"
    
    local index_file="$DOCS_DIR/README.md"
    
    {
        echo "# basir_accounting_system - Documentation"
        echo ""
        echo "**Generated:** $(date)"
        echo "**Flutter Version:** $(flutter --version | head -n 1)"
        echo ""
        echo "## Available Documentation"
        echo ""
        
        if [ -d "$HTML_DIR" ]; then
            echo "### 📚 API Documentation"
            echo "- [HTML Documentation](html/index.html)"
        fi
        
        if [ -f "$PDF_FILE" ]; then
            echo "- [PDF Documentation]($(basename "$PDF_FILE"))"
        fi
        
        if [ -d "$DOCS_DIR/coverage" ]; then
            echo ""
            echo "### 📊 Test Coverage"
            echo "- [Coverage Report](coverage/index.html)"
        fi
        
        echo ""
        echo "## Project Structure"
        echo ""
        echo "\`\`\`"
        echo "lib/"
        find lib -type f -name "*.dart" | head -20
        echo "..."
        echo "\`\`\`"
        
        echo ""
        echo "## Principles Applied"
        echo ""
        echo "- ✅ COLLABORATION FIRST: Clear documentation structure"
        echo "- ✅ KISS: Simple documentation generation"
        echo "- ✅ Security First: No sensitive information exposed"
        echo "- ✅ Quality First: Comprehensive API documentation"
        echo "- ✅ ENGLISH FOR CODE: All documentation in English"
        
        echo ""
        echo "---"
        echo ""
        echo "**Generated by:** Basir Development Agents Team"
        echo "**Date:** $(date +%Y-%m-%d)"
    } > "$index_file"
    
    print_message "$GREEN" "✅ Documentation index created: $index_file"
}

# Generate final report
generate_report() {
    print_header "📊 Documentation Report"
    
    local report_file="$DOCS_DIR/generation-report.txt"
    
    {
        echo "Documentation Generation Report"
        echo "==============================="
        echo ""
        echo "Date: $(date)"
        echo "Flutter Version: $(flutter --version | head -n 1)"
        echo ""
        echo "Generation Status: ✅ Success"
        echo ""
        echo "Generated Files:"
        
        if [ -d "$HTML_DIR" ]; then
            local html_count=$(find "$HTML_DIR" -name "*.html" | wc -l)
            echo "- HTML files: $html_count"
        fi
        
        if [ -f "$PDF_FILE" ]; then
            local pdf_size_kb=$(du -k "$PDF_FILE" | cut -f1)
            echo "- PDF file: $PDF_FILE (${pdf_size_kb}KB)"
        fi
        
        if [ -d "$DOCS_DIR/coverage" ]; then
            echo "- Coverage report: $DOCS_DIR/coverage/"
        fi
        
        echo ""
        echo "Documentation Location: $DOCS_DIR"
        echo ""
        echo "View Documentation:"
        echo "- Open: $HTML_DIR/index.html"
        
        if [ -f "$PDF_FILE" ]; then
            echo "- Open: $PDF_FILE"
        fi
        
        echo ""
        echo "Principles Applied:"
        echo "- ✅ COLLABORATION FIRST: User-friendly documentation"
        echo "- ✅ KISS: Simple generation process"
        echo "- ✅ Security First: No secrets in documentation"
        echo "- ✅ Quality First: Comprehensive coverage"
        echo "- ✅ ENGLISH FOR CODE: All docs in English"
    } > "$report_file"
    
    cat "$report_file"
    print_message "$GREEN" "✅ Report saved to: $report_file"
}

# Main execution
main() {
    print_header "📚 Enhanced Documentation Generator v2.0"
    
    print_message "$BLUE" "Starting documentation generation..."
    echo ""
    
    # Execute generation steps
    pre_generation_checks
    generate_dartdoc
    enhance_html
    generate_pdf
    generate_coverage_docs
    generate_index
    deploy_to_github_pages
    generate_report
    
    print_header "✅ Documentation Generation Completed!"
    
    print_message "$GREEN" "🎉 All steps completed!"
    print_message "$BLUE" "📁 Documentation location: $DOCS_DIR"
    print_message "$BLUE" "🌐 Open: $HTML_DIR/index.html"
}

# Run main function
main "$@"
