[package]
name = "accounting_zatca"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31", features = ["serialize"] }
base64 = "0.21"
p256 = { version = "0.13", features = ["ecdsa", "std", "pem"] }
sha2 = "0.10"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
hex = "0.4"
rand = "0.8.5"
rust_decimal.workspace = true
rcgen = "0.14.6"
