[package]
name = "accounting_zatca"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
quick-xml = { version = "0.31", features = ["serialize"] }
base64 = "0.21"
p256 = { version = "0.13", features = ["ecdsa", "std", "pem"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
rand = "0.8.5"
rust_decimal = { workspace = true }
rcgen = "0.14.6"
