// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/frb_generated.dart/api.dart';
import 'package:basir_app/src/rust/frb_generated.dart/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<String> createAccount(
        {required AccountDto dto, required AuditMetadataDto metadata}) =>
    RustLib.instance.api
        .crateApiAccountsCreateAccount(dto: dto, metadata: metadata);

Future<void> updateAccount(
        {required AccountDto dto, required AuditMetadataDto metadata}) =>
    RustLib.instance.api
        .crateApiAccountsUpdateAccount(dto: dto, metadata: metadata);

Future<List<AccountDto>> listAccounts() =>
    RustLib.instance.api.crateApiAccountsListAccounts();

Future<AccountDto?> getAccountById({required String id}) =>
    RustLib.instance.api.crateApiAccountsGetAccountById(id: id);

Future<void> updateAccountCategory({
  required String accountId,
  required String category,
  required AuditMetadataDto metadata,
}) =>
    RustLib.instance.api.crateApiAccountsUpdateAccountCategory(
      accountId: accountId,
      category: category,
      metadata: metadata,
    );

/// DTO for Account
class AccountDto {
  const AccountDto({
    required this.id,
    required this.code,
    required this.nameAr,
    required this.nameEn,
    required this.kind,
    required this.ifrs18Category,
    required this.currency,
    this.parentId,
    this.ifrsTag,
    this.classification,
  });
  final String id;
  final String code;
  final String nameAr;
  final String nameEn;
  final String kind;
  final String? parentId;
  final String? ifrsTag;
  final String? classification;
  final String ifrs18Category;
  final String currency;

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      kind.hashCode ^
      parentId.hashCode ^
      ifrsTag.hashCode ^
      classification.hashCode ^
      ifrs18Category.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          kind == other.kind &&
          parentId == other.parentId &&
          ifrsTag == other.ifrsTag &&
          classification == other.classification &&
          ifrs18Category == other.ifrs18Category &&
          currency == other.currency;
}
