// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/frb_generated.dart/api.dart';
import 'package:basir_app/src/rust/frb_generated.dart/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `from`, `from`, `try_from`, `try_from`

Future<String> registerAsset({required AssetDto asset}) =>
    RustLib.instance.api.crateApiAssetsRegisterAsset(asset: asset);

Future<List<AssetDto>> listAssets() =>
    RustLib.instance.api.crateApiAssetsListAssets();

Future<AssetDto?> getAssetById({required String id}) =>
    RustLib.instance.api.crateApiAssetsGetAssetById(id: id);

Future<void> runDepreciationCycle(
        {required String assetId,
        required String asOf,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiAssetsRunDepreciationCycle(
        assetId: assetId, asOf: asOf, metadata: metadata);

Future<String> registerCategory({required AssetCategoryDto category}) =>
    RustLib.instance.api.crateApiAssetsRegisterCategory(category: category);

Future<List<AssetCategoryDto>> listCategories() =>
    RustLib.instance.api.crateApiAssetsListCategories();

class AssetCategoryDto {
  const AssetCategoryDto({
    required this.nameAr,
    required this.nameEn,
    required this.defaultDepreciationMethod,
    required this.defaultUsefulLifeYears,
    required this.assetAccountId,
    required this.depreciationAccountId,
    required this.accumDepreciationAccountId,
    this.id,
  });
  final String? id;
  final String nameAr;
  final String nameEn;
  final String defaultDepreciationMethod;
  final int defaultUsefulLifeYears;
  final String assetAccountId;
  final String depreciationAccountId;
  final String accumDepreciationAccountId;

  @override
  int get hashCode =>
      id.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      defaultDepreciationMethod.hashCode ^
      defaultUsefulLifeYears.hashCode ^
      assetAccountId.hashCode ^
      depreciationAccountId.hashCode ^
      accumDepreciationAccountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetCategoryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          defaultDepreciationMethod == other.defaultDepreciationMethod &&
          defaultUsefulLifeYears == other.defaultUsefulLifeYears &&
          assetAccountId == other.assetAccountId &&
          depreciationAccountId == other.depreciationAccountId &&
          accumDepreciationAccountId == other.accumDepreciationAccountId;
}

class AssetDto {
  const AssetDto({
    required this.code,
    required this.nameAr,
    required this.nameEn,
    required this.categoryId,
    required this.acquisitionDate,
    required this.cost,
    required this.residualValue,
    required this.usefulLifeYears,
    required this.depreciationMethod,
    required this.accumulatedDepreciation,
    required this.assetAccountId,
    required this.depreciationAccountId,
    required this.accumDepreciationAccountId,
    required this.isActive,
    this.id,
  });
  final String? id;
  final String code;
  final String nameAr;
  final String nameEn;
  final String categoryId;
  final String acquisitionDate;
  final String cost;
  final String residualValue;
  final int usefulLifeYears;
  final String depreciationMethod;
  final String accumulatedDepreciation;
  final String assetAccountId;
  final String depreciationAccountId;
  final String accumDepreciationAccountId;
  final bool isActive;

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      categoryId.hashCode ^
      acquisitionDate.hashCode ^
      cost.hashCode ^
      residualValue.hashCode ^
      usefulLifeYears.hashCode ^
      depreciationMethod.hashCode ^
      accumulatedDepreciation.hashCode ^
      assetAccountId.hashCode ^
      depreciationAccountId.hashCode ^
      accumDepreciationAccountId.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          categoryId == other.categoryId &&
          acquisitionDate == other.acquisitionDate &&
          cost == other.cost &&
          residualValue == other.residualValue &&
          usefulLifeYears == other.usefulLifeYears &&
          depreciationMethod == other.depreciationMethod &&
          accumulatedDepreciation == other.accumulatedDepreciation &&
          assetAccountId == other.assetAccountId &&
          depreciationAccountId == other.depreciationAccountId &&
          accumDepreciationAccountId == other.accumDepreciationAccountId &&
          isActive == other.isActive;
}
