// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/frb_generated.dart/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> savePeriod({required PeriodDto dto}) =>
    RustLib.instance.api.crateApiCalendarSavePeriod(dto: dto);

Future<PeriodDto?> getPeriodByDate({required String date}) =>
    RustLib.instance.api.crateApiCalendarGetPeriodByDate(date: date);

Future<void> closePeriod({required String id, required String userId}) =>
    RustLib.instance.api.crateApiCalendarClosePeriod(id: id, userId: userId);

Future<List<PeriodDto>> listPeriods() =>
    RustLib.instance.api.crateApiCalendarListPeriods();

Future<String> closeFinancialYear(
        {required String periodId,
        required String closingDate,
        required String retainedEarningsAccountId}) =>
    RustLib.instance.api.crateApiCalendarCloseFinancialYear(
        periodId: periodId,
        closingDate: closingDate,
        retainedEarningsAccountId: retainedEarningsAccountId);

class PeriodDto {
  const PeriodDto({
    required this.name,
    required this.startDate,
    required this.endDate,
    required this.status,
    required this.isYearEnd,
    this.id,
  });
  final String? id;
  final String name;
  final String startDate;
  final String endDate;
  final String status;
  final bool isYearEnd;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      status.hashCode ^
      isYearEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeriodDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          status == other.status &&
          isYearEnd == other.isYearEnd;
}
