// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/frb_generated.dart/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Look up a standard by reference string (e.g. "IFRS 15.35")
Future<StandardDto> getStandardInfo({required String reference}) =>
    RustLib.instance.api.crateApiStandardsGetStandardInfo(reference: reference);

/// Search for standards by keyword
Future<List<StandardDto>> searchStandards({required String query}) =>
    RustLib.instance.api.crateApiStandardsSearchStandards(query: query);

/// Simple DTO for Standard lookup result
class StandardDto {
  const StandardDto({
    required this.reference,
    required this.title,
    required this.isEffective,
  });
  final String reference;
  final String title;
  final bool isEffective;

  @override
  int get hashCode =>
      reference.hashCode ^ title.hashCode ^ isEffective.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StandardDto &&
          runtimeType == other.runtimeType &&
          reference == other.reference &&
          title == other.title &&
          isEffective == other.isEffective;
}
