// Mocks generated by Mockito 5.4.4 from annotations
// in basir_accounting_system/test/mocks/app_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:basir_accounting_system/features/customers/domain/entities/customer.dart'
    as _i6;
import 'package:basir_accounting_system/features/customers/domain/repositories/customer_repository.dart'
    as _i4;
import 'package:basir_accounting_system/features/invoices/domain/entities/invoice.dart'
    as _i3;
import 'package:basir_accounting_system/features/invoices/domain/entities/invoice_status.dart'
    as _i7;
import 'package:basir_accounting_system/features/invoices/domain/repositories/invoice_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInvoiceStatistics_0 extends _i1.SmartFake
    implements _i2.InvoiceStatistics {
  _FakeInvoiceStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoice_1 extends _i1.SmartFake implements _i3.Invoice {
  _FakeInvoice_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i4.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Customer>> getAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomers,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Customer>>.value(<_i6.Customer>[]),
      ) as _i5.Future<List<_i6.Customer>>);

  @override
  _i5.Future<_i6.Customer?> getCustomerById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCustomerById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Customer?>.value(),
      ) as _i5.Future<_i6.Customer?>);

  @override
  _i5.Future<List<_i6.Customer>> searchCustomers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCustomers,
          [query],
        ),
        returnValue: _i5.Future<List<_i6.Customer>>.value(<_i6.Customer>[]),
      ) as _i5.Future<List<_i6.Customer>>);

  @override
  _i5.Future<void> addCustomer(_i6.Customer? customer) => (super.noSuchMethod(
        Invocation.method(
          #addCustomer,
          [customer],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCustomer(_i6.Customer? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomer,
          [customer],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCustomer(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomer,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCustomers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [InvoiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoiceRepository extends _i1.Mock implements _i2.InvoiceRepository {
  MockInvoiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Invoice>> getAllInvoices() => (super.noSuchMethod(
        Invocation.method(
          #getAllInvoices,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Invoice>>.value(<_i3.Invoice>[]),
      ) as _i5.Future<List<_i3.Invoice>>);

  @override
  _i5.Future<_i3.Invoice?> getInvoiceById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getInvoiceById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Invoice?>.value(),
      ) as _i5.Future<_i3.Invoice?>);

  @override
  _i5.Future<List<_i3.Invoice>> getInvoicesByCustomerId(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesByCustomerId,
          [customerId],
        ),
        returnValue: _i5.Future<List<_i3.Invoice>>.value(<_i3.Invoice>[]),
      ) as _i5.Future<List<_i3.Invoice>>);

  @override
  _i5.Future<List<_i3.Invoice>> getInvoicesByStatus(
          _i7.InvoiceStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoicesByStatus,
          [status],
        ),
        returnValue: _i5.Future<List<_i3.Invoice>>.value(<_i3.Invoice>[]),
      ) as _i5.Future<List<_i3.Invoice>>);

  @override
  _i5.Future<void> addInvoice(_i3.Invoice? invoice) => (super.noSuchMethod(
        Invocation.method(
          #addInvoice,
          [invoice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateInvoice(_i3.Invoice? invoice) => (super.noSuchMethod(
        Invocation.method(
          #updateInvoice,
          [invoice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteInvoice(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteInvoice,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllInvoices() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllInvoices,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.InvoiceStatistics> getInvoiceStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvoiceStatistics,
          [],
        ),
        returnValue:
            _i5.Future<_i2.InvoiceStatistics>.value(_FakeInvoiceStatistics_0(
          this,
          Invocation.method(
            #getInvoiceStatistics,
            [],
          ),
        )),
      ) as _i5.Future<_i2.InvoiceStatistics>);

  @override
  _i5.Future<_i3.Invoice> duplicateInvoice(String? id) => (super.noSuchMethod(
        Invocation.method(
          #duplicateInvoice,
          [id],
        ),
        returnValue: _i5.Future<_i3.Invoice>.value(_FakeInvoice_1(
          this,
          Invocation.method(
            #duplicateInvoice,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Invoice>);
}
