#!/bin/bash
# Script: generate_quality_report.sh
# Purpose: Generate a comprehensive quality report (Diamond Purity Standards).
# Author: Antigravity

set -e

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_DIR="logs/reports"
REPORT_FILE="$REPORT_DIR/quality_report_$TIMESTAMP.md"
LATEST_REPORT="$REPORT_DIR/latest_report.md"

mkdir -p "$REPORT_DIR"

echo "# 📊 Basir Quality Report - $TIMESTAMP" > "$REPORT_FILE"
echo "Generated by Elite Quality Engine." >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

echo "## 1. 🔍 Static Analysis (Flutter Analyze)" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
flutter analyze >> "$REPORT_FILE" 2>&1 || echo "Analysis found issues." >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

echo "## 2. 🧪 Unit & Widget Tests" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
flutter test --reporter=compact >> "$REPORT_FILE" 2>&1 || echo "Some tests failed." >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

echo "## 3. 🛡️ Branding Consistency" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
./scripts/verify_branding.sh >> "$REPORT_FILE" 2>&1
echo '```' >> "$REPORT_FILE"

echo "---" >> "$REPORT_FILE"
echo "Report saved to $REPORT_FILE"

# Create/Update symlink to latest
ln -sf "quality_report_$TIMESTAMP.md" "$LATEST_REPORT"

echo "✨ Quality report generated: $REPORT_FILE"
echo "🔗 Link: $LATEST_REPORT"
