// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ledger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'auditor.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

List<AnomalyDto> scanSequence(
        {required String prefix, required List<EntryDto> entries}) =>
    RustLib.instance.api
        .crateApiAuditorScanSequence(prefix: prefix, entries: entries);

@freezed
sealed class AnomalyDto with _$AnomalyDto {
  const AnomalyDto._();

  const factory AnomalyDto.sequenceGap({
    required String expected,
    required String found,
  }) = AnomalyDto_SequenceGap;
  const factory AnomalyDto.reconciliationMismatch({
    required String accountId,
    required String bookBalance,
    required String physicalCount,
  }) = AnomalyDto_ReconciliationMismatch;
  const factory AnomalyDto.orphanedDraft({
    required String entryId,
    required String date,
  }) = AnomalyDto_OrphanedDraft;
}
