// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> saveExchangeRate({required ExchangeRateDto dto}) =>
    RustLib.instance.api.crateApiCurrencySaveExchangeRate(dto: dto);

Future<ExchangeRateDto?> getExchangeRate(
        {required String base, required String target, required String date}) =>
    RustLib.instance.api.crateApiCurrencyGetExchangeRate(
        base: base, target: target, date: date);

Future<List<ExchangeRateDto>> listExchangeRates(
        {String? base, String? target}) =>
    RustLib.instance.api
        .crateApiCurrencyListExchangeRates(base: base, target: target);

Future<String> performRevaluation(
        {required String date,
        required String systemBase,
        required String unrealizedGainLossAccountId,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiCurrencyPerformRevaluation(
        date: date,
        systemBase: systemBase,
        unrealizedGainLossAccountId: unrealizedGainLossAccountId,
        metadata: metadata);

class ExchangeRateDto {
  final String baseCurrency;
  final String targetCurrency;
  final String rate;
  final String effectiveDate;
  final String? source;

  const ExchangeRateDto({
    required this.baseCurrency,
    required this.targetCurrency,
    required this.rate,
    required this.effectiveDate,
    this.source,
  });

  @override
  int get hashCode =>
      baseCurrency.hashCode ^
      targetCurrency.hashCode ^
      rate.hashCode ^
      effectiveDate.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExchangeRateDto &&
          runtimeType == other.runtimeType &&
          baseCurrency == other.baseCurrency &&
          targetCurrency == other.targetCurrency &&
          rate == other.rate &&
          effectiveDate == other.effectiveDate &&
          source == other.source;
}
