// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`, `from`, `try_from`, `try_from`

Future<List<InventoryItemDto>> listItems() =>
    RustLib.instance.api.crateApiInventoryListItems();

Future<InventoryItemDto?> getItemById({required String id}) =>
    RustLib.instance.api.crateApiInventoryGetItemById(id: id);

Future<void> saveItem({required InventoryItemDto item}) =>
    RustLib.instance.api.crateApiInventorySaveItem(item: item);

Future<String> recordMovement(
        {required StockMovementDto movement,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiInventoryRecordMovement(
        movement: movement, metadata: metadata);

Future<String> recordPurchase(
        {required String itemId,
        required String quantity,
        required String unitCost,
        String? referenceId,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiInventoryRecordPurchase(
        itemId: itemId,
        quantity: quantity,
        unitCost: unitCost,
        referenceId: referenceId,
        metadata: metadata);

Future<String> recordSale(
        {required String itemId,
        required String quantity,
        String? referenceId,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiInventoryRecordSale(
        itemId: itemId,
        quantity: quantity,
        referenceId: referenceId,
        metadata: metadata);

Future<String> recordImpairment(
        {required String itemId,
        required String totalImpairmentAmount,
        String? referenceId,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiInventoryRecordImpairment(
        itemId: itemId,
        totalImpairmentAmount: totalImpairmentAmount,
        referenceId: referenceId,
        metadata: metadata);

Future<bool> verifyInventoryChain({required String itemId}) =>
    RustLib.instance.api.crateApiInventoryVerifyInventoryChain(itemId: itemId);

Future<InventoryValuationReportDto> getValuationReport(
        {required String asOf}) =>
    RustLib.instance.api.crateApiInventoryGetValuationReport(asOf: asOf);

Future<List<StockMovementDto>> listMovements({required String itemId}) =>
    RustLib.instance.api.crateApiInventoryListMovements(itemId: itemId);

class InventoryItemDto {
  final String? id;
  final String code;
  final String nameAr;
  final String nameEn;
  final String? description;
  final String unit;
  final String valuationMethod;
  final String? purchasePrice;
  final String? salePrice;
  final String assetAccountId;
  final String cogsAccountId;
  final String revenueAccountId;
  final String createdAt;
  final String updatedAt;

  const InventoryItemDto({
    this.id,
    required this.code,
    required this.nameAr,
    required this.nameEn,
    this.description,
    required this.unit,
    required this.valuationMethod,
    this.purchasePrice,
    this.salePrice,
    required this.assetAccountId,
    required this.cogsAccountId,
    required this.revenueAccountId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      description.hashCode ^
      unit.hashCode ^
      valuationMethod.hashCode ^
      purchasePrice.hashCode ^
      salePrice.hashCode ^
      assetAccountId.hashCode ^
      cogsAccountId.hashCode ^
      revenueAccountId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          description == other.description &&
          unit == other.unit &&
          valuationMethod == other.valuationMethod &&
          purchasePrice == other.purchasePrice &&
          salePrice == other.salePrice &&
          assetAccountId == other.assetAccountId &&
          cogsAccountId == other.cogsAccountId &&
          revenueAccountId == other.revenueAccountId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class InventoryValuationReportDto {
  final String asOf;
  final List<ValuationItemDto> items;
  final String totalValue;

  const InventoryValuationReportDto({
    required this.asOf,
    required this.items,
    required this.totalValue,
  });

  @override
  int get hashCode => asOf.hashCode ^ items.hashCode ^ totalValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryValuationReportDto &&
          runtimeType == other.runtimeType &&
          asOf == other.asOf &&
          items == other.items &&
          totalValue == other.totalValue;
}

class StockMovementDto {
  final String? id;
  final String itemId;
  final String movementType;
  final String quantity;
  final String unitCost;
  final String? referenceId;
  final String date;
  final String? description;

  const StockMovementDto({
    this.id,
    required this.itemId,
    required this.movementType,
    required this.quantity,
    required this.unitCost,
    this.referenceId,
    required this.date,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      itemId.hashCode ^
      movementType.hashCode ^
      quantity.hashCode ^
      unitCost.hashCode ^
      referenceId.hashCode ^
      date.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StockMovementDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemId == other.itemId &&
          movementType == other.movementType &&
          quantity == other.quantity &&
          unitCost == other.unitCost &&
          referenceId == other.referenceId &&
          date == other.date &&
          description == other.description;
}

class ValuationItemDto {
  final String itemId;
  final String itemNameAr;
  final String itemNameEn;
  final String quantity;
  final String unitCost;
  final String totalValue;

  const ValuationItemDto({
    required this.itemId,
    required this.itemNameAr,
    required this.itemNameEn,
    required this.quantity,
    required this.unitCost,
    required this.totalValue,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      itemNameAr.hashCode ^
      itemNameEn.hashCode ^
      quantity.hashCode ^
      unitCost.hashCode ^
      totalValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValuationItemDto &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          itemNameAr == other.itemNameAr &&
          itemNameEn == other.itemNameEn &&
          quantity == other.quantity &&
          unitCost == other.unitCost &&
          totalValue == other.totalValue;
}
