// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_entity_to_dto`

/// Validate a journal entry (CP-001, CP-002, CP-010)
Future<void> validateJournalEntry({required EntryDto dto}) =>
    RustLib.instance.api.crateApiLedgerValidateJournalEntry(dto: dto);

/// List journal entries with pagination
Future<List<EntryDto>> listJournalEntries(
        {required PlatformInt64 limit,
        required PlatformInt64 offset,
        String? fromDate,
        String? toDate,
        String? accountId}) =>
    RustLib.instance.api.crateApiLedgerListJournalEntries(
        limit: limit,
        offset: offset,
        fromDate: fromDate,
        toDate: toDate,
        accountId: accountId);

/// Post a journal entry to the database
Future<String> postJournalEntry(
        {required EntryDto dto, required AuditMetadataDto metadata}) =>
    RustLib.instance.api
        .crateApiLedgerPostJournalEntry(dto: dto, metadata: metadata);

/// Reverse a journal entry
Future<String> reverseJournalEntry(
        {required String entryId,
        required String reason,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiLedgerReverseJournalEntry(
        entryId: entryId, reason: reason, metadata: metadata);

/// Log the cognitive agent consensus for a journal entry
Future<void> logAgentConsensus(
        {required String entryId,
        required String consensusJson,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiLedgerLogAgentConsensus(
        entryId: entryId, consensusJson: consensusJson, metadata: metadata);

/// Retrieve the cognitive agent consensus for a journal entry
Future<String?> getAgentConsensus({required String entryId}) =>
    RustLib.instance.api.crateApiLedgerGetAgentConsensus(entryId: entryId);

/// List all audit records for a specific entity
Future<List<AuditRecordDto>> listAuditLogs({required String entityId}) =>
    RustLib.instance.api.crateApiLedgerListAuditLogs(entityId: entityId);

Future<JournalEntry> mapDtoToEntity({required EntryDto dto}) =>
    RustLib.instance.api.crateApiLedgerMapDtoToEntity(dto: dto);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JournalEntry>>
abstract class JournalEntry implements RustOpaqueInterface {}

class EntryDto {
  final String? entryId;
  final String entryNumber;
  final String description;
  final String date;
  final String standardRef;
  final List<LineDto> lines;
  final String? linkedEntryId;
  final String? adjustmentReason;

  const EntryDto({
    this.entryId,
    required this.entryNumber,
    required this.description,
    required this.date,
    required this.standardRef,
    required this.lines,
    this.linkedEntryId,
    this.adjustmentReason,
  });

  @override
  int get hashCode =>
      entryId.hashCode ^
      entryNumber.hashCode ^
      description.hashCode ^
      date.hashCode ^
      standardRef.hashCode ^
      lines.hashCode ^
      linkedEntryId.hashCode ^
      adjustmentReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDto &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          entryNumber == other.entryNumber &&
          description == other.description &&
          date == other.date &&
          standardRef == other.standardRef &&
          lines == other.lines &&
          linkedEntryId == other.linkedEntryId &&
          adjustmentReason == other.adjustmentReason;
}

class LineDto {
  final String accountId;
  final String amount;
  final bool isDebit;
  final String description;
  final String? originalCurrency;
  final String? exchangeRate;
  final String? originalAmount;

  const LineDto({
    required this.accountId,
    required this.amount,
    required this.isDebit,
    required this.description,
    this.originalCurrency,
    this.exchangeRate,
    this.originalAmount,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      amount.hashCode ^
      isDebit.hashCode ^
      description.hashCode ^
      originalCurrency.hashCode ^
      exchangeRate.hashCode ^
      originalAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          amount == other.amount &&
          isDebit == other.isDebit &&
          description == other.description &&
          originalCurrency == other.originalCurrency &&
          exchangeRate == other.exchangeRate &&
          originalAmount == other.originalAmount;
}
