// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`, `try_from`, `try_from`

Future<List<VendorDto>> listVendors() =>
    RustLib.instance.api.crateApiPurchasingListVendors();

Future<VendorDto?> getVendorById({required String id}) =>
    RustLib.instance.api.crateApiPurchasingGetVendorById(id: id);

Future<String> createVendor({required VendorDto vendor}) =>
    RustLib.instance.api.crateApiPurchasingCreateVendor(vendor: vendor);

Future<void> updateVendor({required VendorDto vendor}) =>
    RustLib.instance.api.crateApiPurchasingUpdateVendor(vendor: vendor);

Future<void> deleteVendor({required String id}) =>
    RustLib.instance.api.crateApiPurchasingDeleteVendor(id: id);

Future<List<PurchaseBillDto>> listPurchaseBills() =>
    RustLib.instance.api.crateApiPurchasingListPurchaseBills();

Future<PurchaseBillDto?> getPurchaseBillById({required String id}) =>
    RustLib.instance.api.crateApiPurchasingGetPurchaseBillById(id: id);

Future<void> deleteBill({required String id}) =>
    RustLib.instance.api.crateApiPurchasingDeleteBill(id: id);

Future<String> createPurchaseBill(
        {required PurchaseBillDto bill, required AuditMetadataDto metadata}) =>
    RustLib.instance.api
        .crateApiPurchasingCreatePurchaseBill(bill: bill, metadata: metadata);

Future<void> recordBillPayment(
        {required BillPaymentDto payment,
        required AuditMetadataDto metadata}) =>
    RustLib.instance.api.crateApiPurchasingRecordBillPayment(
        payment: payment, metadata: metadata);

class BillPaymentDto {
  final String? id;
  final String billId;
  final String amount;
  final String paymentDate;
  final String paymentMethod;
  final String bankAccountId;
  final String? reference;

  const BillPaymentDto({
    this.id,
    required this.billId,
    required this.amount,
    required this.paymentDate,
    required this.paymentMethod,
    required this.bankAccountId,
    this.reference,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      billId.hashCode ^
      amount.hashCode ^
      paymentDate.hashCode ^
      paymentMethod.hashCode ^
      bankAccountId.hashCode ^
      reference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillPaymentDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          billId == other.billId &&
          amount == other.amount &&
          paymentDate == other.paymentDate &&
          paymentMethod == other.paymentMethod &&
          bankAccountId == other.bankAccountId &&
          reference == other.reference;
}

class PurchaseBillDto {
  final String? id;
  final String billNumber;
  final String vendorId;
  final String billDate;
  final String dueDate;
  final String totalAmount;
  final String balanceDue;
  final String status;
  final String expenseAccountId;
  final String apAccountId;
  final String? description;

  const PurchaseBillDto({
    this.id,
    required this.billNumber,
    required this.vendorId,
    required this.billDate,
    required this.dueDate,
    required this.totalAmount,
    required this.balanceDue,
    required this.status,
    required this.expenseAccountId,
    required this.apAccountId,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      billNumber.hashCode ^
      vendorId.hashCode ^
      billDate.hashCode ^
      dueDate.hashCode ^
      totalAmount.hashCode ^
      balanceDue.hashCode ^
      status.hashCode ^
      expenseAccountId.hashCode ^
      apAccountId.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PurchaseBillDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          billNumber == other.billNumber &&
          vendorId == other.vendorId &&
          billDate == other.billDate &&
          dueDate == other.dueDate &&
          totalAmount == other.totalAmount &&
          balanceDue == other.balanceDue &&
          status == other.status &&
          expenseAccountId == other.expenseAccountId &&
          apAccountId == other.apAccountId &&
          description == other.description;
}

class VendorDto {
  final String? id;
  final String code;
  final String nameAr;
  final String nameEn;
  final String? taxId;

  const VendorDto({
    this.id,
    required this.code,
    required this.nameAr,
    required this.nameEn,
    this.taxId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      taxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VendorDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          taxId == other.taxId;
}
