// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Ifrs18IncomeStatementDto`, `ManagementPerformanceMeasureDto`

/// Generate a trial balance (Task 16.1, 16.2)
Future<TrialBalanceDto> generateTrialBalance({
  required String asOfDate,
  String? periodStart,
}) =>
    RustLib.instance.api.crateApiReportsGenerateTrialBalance(
      asOfDate: asOfDate,
      periodStart: periodStart,
    );

/// Drill down into account entries (Task 16.3)
Future<List<DrillDownEntryDto>> getAccountEntries({
  required String accountId,
  required String periodEnd,
  String? periodStart,
}) =>
    RustLib.instance.api.crateApiReportsGetAccountEntries(
      accountId: accountId,
      periodStart: periodStart,
      periodEnd: periodEnd,
    );

/// Generate an Income Statement (Task 16.2 extension)
Future<FinancialReportDto> generateIncomeStatement({
  required String fromDate,
  required String toDate,
}) =>
    RustLib.instance.api.crateApiReportsGenerateIncomeStatement(
      fromDate: fromDate,
      toDate: toDate,
    );

/// Generate a Balance Sheet (Task 16.2 extension)
Future<FinancialReportDto> generateBalanceSheet({required String asOfDate}) =>
    RustLib.instance.api
        .crateApiReportsGenerateBalanceSheet(asOfDate: asOfDate);

/// Generate a Statement of Cash Flows (Task 14.2)
Future<FinancialReportDto> generateCashFlowStatement({
  required String fromDate,
  required String toDate,
}) =>
    RustLib.instance.api.crateApiReportsGenerateCashFlowStatement(
      fromDate: fromDate,
      toDate: toDate,
    );

/// Generate a Zakah Statement (Task 14.3)
Future<FinancialReportDto> generateZakahStatement({
  required String asOfDate,
  required ZakahCalendarDto calendar,
}) =>
    RustLib.instance.api.crateApiReportsGenerateZakahStatement(
      asOfDate: asOfDate,
      calendar: calendar,
    );

/// Generate Accounts Receivable Aging Report
Future<List<AgingReportLineDto>> getReceivablesAging({
  required String asOfDate,
}) =>
    RustLib.instance.api.crateApiReportsGetReceivablesAging(asOfDate: asOfDate);

/// Generate Accounts Payable Aging Report
Future<List<AgingReportLineDto>> getPayablesAging({required String asOfDate}) =>
    RustLib.instance.api.crateApiReportsGetPayablesAging(asOfDate: asOfDate);

/// DTO for Aging Reports
class AgingReportLineDto {
  const AgingReportLineDto({
    required this.partnerId,
    required this.partnerName,
    required this.currentAmount,
    required this.period130,
    required this.period3160,
    required this.period6190,
    required this.periodOver90,
    required this.totalAmount,
  });
  final String partnerId;
  final String partnerName;
  final String currentAmount;
  final String period130;
  final String period3160;
  final String period6190;
  final String periodOver90;
  final String totalAmount;

  @override
  int get hashCode =>
      partnerId.hashCode ^
      partnerName.hashCode ^
      currentAmount.hashCode ^
      period130.hashCode ^
      period3160.hashCode ^
      period6190.hashCode ^
      periodOver90.hashCode ^
      totalAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgingReportLineDto &&
          runtimeType == other.runtimeType &&
          partnerId == other.partnerId &&
          partnerName == other.partnerName &&
          currentAmount == other.currentAmount &&
          period130 == other.period130 &&
          period3160 == other.period3160 &&
          period6190 == other.period6190 &&
          periodOver90 == other.periodOver90 &&
          totalAmount == other.totalAmount;
}

class DrillDownEntryDto {
  const DrillDownEntryDto({
    required this.entryId,
    required this.entryNumber,
    required this.effectiveDate,
    required this.description,
    required this.debit,
    required this.credit,
    this.standardReference,
  });
  final String entryId;
  final String entryNumber;
  final String effectiveDate;
  final String description;
  final String debit;
  final String credit;
  final String? standardReference;

  @override
  int get hashCode =>
      entryId.hashCode ^
      entryNumber.hashCode ^
      effectiveDate.hashCode ^
      description.hashCode ^
      debit.hashCode ^
      credit.hashCode ^
      standardReference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrillDownEntryDto &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          entryNumber == other.entryNumber &&
          effectiveDate == other.effectiveDate &&
          description == other.description &&
          debit == other.debit &&
          credit == other.credit &&
          standardReference == other.standardReference;
}

class FinancialReportDto {
  const FinancialReportDto({
    required this.title,
    required this.fromDate,
    required this.toDate,
    required this.lines,
    required this.generatedAt,
  });
  final String title;
  final String fromDate;
  final String toDate;
  final List<FinancialReportLineDto> lines;
  final String generatedAt;

  @override
  int get hashCode =>
      title.hashCode ^
      fromDate.hashCode ^
      toDate.hashCode ^
      lines.hashCode ^
      generatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinancialReportDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          fromDate == other.fromDate &&
          toDate == other.toDate &&
          lines == other.lines &&
          generatedAt == other.generatedAt;
}

class FinancialReportLineDto {
  const FinancialReportLineDto({
    required this.label,
    required this.amount,
    required this.isTitle,
    required this.isTotal,
    required this.indentLevel,
  });
  final String label;
  final String amount;
  final bool isTitle;
  final bool isTotal;
  final int indentLevel;

  @override
  int get hashCode =>
      label.hashCode ^
      amount.hashCode ^
      isTitle.hashCode ^
      isTotal.hashCode ^
      indentLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinancialReportLineDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          amount == other.amount &&
          isTitle == other.isTitle &&
          isTotal == other.isTotal &&
          indentLevel == other.indentLevel;
}

class TrialBalanceDto {
  const TrialBalanceDto({
    required this.asOfDate,
    required this.periodEnd,
    required this.lines,
    required this.totalDebits,
    required this.totalCredits,
    required this.isBalanced,
    this.periodStart,
  });
  final String asOfDate;
  final String? periodStart;
  final String periodEnd;
  final List<TrialBalanceLineDto> lines;
  final String totalDebits;
  final String totalCredits;
  final bool isBalanced;

  @override
  int get hashCode =>
      asOfDate.hashCode ^
      periodStart.hashCode ^
      periodEnd.hashCode ^
      lines.hashCode ^
      totalDebits.hashCode ^
      totalCredits.hashCode ^
      isBalanced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrialBalanceDto &&
          runtimeType == other.runtimeType &&
          asOfDate == other.asOfDate &&
          periodStart == other.periodStart &&
          periodEnd == other.periodEnd &&
          lines == other.lines &&
          totalDebits == other.totalDebits &&
          totalCredits == other.totalCredits &&
          isBalanced == other.isBalanced;
}

class TrialBalanceLineDto {
  const TrialBalanceLineDto({
    required this.accountId,
    required this.accountCode,
    required this.accountName,
    required this.debitBalance,
    required this.creditBalance,
  });
  final String accountId;
  final String accountCode;
  final String accountName;
  final String debitBalance;
  final String creditBalance;

  @override
  int get hashCode =>
      accountId.hashCode ^
      accountCode.hashCode ^
      accountName.hashCode ^
      debitBalance.hashCode ^
      creditBalance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrialBalanceLineDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          accountCode == other.accountCode &&
          accountName == other.accountName &&
          debitBalance == other.debitBalance &&
          creditBalance == other.creditBalance;
}

enum ZakahCalendarDto {
  hijri,
  gregorian,
  ;
}
