// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:basir_app/src/rust/api.dart';
import 'package:basir_app/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`, `try_from`, `try_from`, `try_from`

Future<List<CustomerDto>> listCustomers() =>
    RustLib.instance.api.crateApiSalesListCustomers();

Future<String> createCustomer({required CustomerDto customer}) =>
    RustLib.instance.api.crateApiSalesCreateCustomer(customer: customer);

Future<void> updateCustomer({required CustomerDto customer}) =>
    RustLib.instance.api.crateApiSalesUpdateCustomer(customer: customer);

Future<void> deleteCustomer({required String id}) =>
    RustLib.instance.api.crateApiSalesDeleteCustomer(id: id);

Future<List<SalesInvoiceDto>> listInvoices() =>
    RustLib.instance.api.crateApiSalesListInvoices();

Future<SalesInvoiceDto?> getInvoiceById({required String id}) =>
    RustLib.instance.api.crateApiSalesGetInvoiceById(id: id);

Future<void> deleteInvoice({required String id}) =>
    RustLib.instance.api.crateApiSalesDeleteInvoice(id: id);

Future<String> createInvoice({
  required SalesInvoiceDto invoice,
  required List<SalesInvoiceLineDto> lines,
  required AuditMetadataDto metadata,
}) =>
    RustLib.instance.api.crateApiSalesCreateInvoice(
      invoice: invoice,
      lines: lines,
      metadata: metadata,
    );

Future<void> postInvoice({
  required String id,
  required AuditMetadataDto metadata,
}) =>
    RustLib.instance.api.crateApiSalesPostInvoice(id: id, metadata: metadata);

Future<void> recordCustomerPayment({
  required CustomerPaymentDto payment,
  required AuditMetadataDto metadata,
}) =>
    RustLib.instance.api.crateApiSalesRecordCustomerPayment(
      payment: payment,
      metadata: metadata,
    );

class CustomerDto {
  const CustomerDto({
    required this.code,
    required this.nameAr,
    required this.nameEn,
    this.id,
    this.taxId,
  });
  final String? id;
  final String code;
  final String nameAr;
  final String nameEn;
  final String? taxId;

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      nameAr.hashCode ^
      nameEn.hashCode ^
      taxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          nameAr == other.nameAr &&
          nameEn == other.nameEn &&
          taxId == other.taxId;
}

class CustomerPaymentDto {
  const CustomerPaymentDto({
    required this.invoiceId,
    required this.amount,
    required this.paymentDate,
    required this.bankAccountId,
    required this.paymentMethod,
    this.id,
    this.reference,
  });
  final String? id;
  final String invoiceId;
  final String amount;
  final String paymentDate;
  final String bankAccountId;
  final String paymentMethod;
  final String? reference;

  @override
  int get hashCode =>
      id.hashCode ^
      invoiceId.hashCode ^
      amount.hashCode ^
      paymentDate.hashCode ^
      bankAccountId.hashCode ^
      paymentMethod.hashCode ^
      reference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerPaymentDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          invoiceId == other.invoiceId &&
          amount == other.amount &&
          paymentDate == other.paymentDate &&
          bankAccountId == other.bankAccountId &&
          paymentMethod == other.paymentMethod &&
          reference == other.reference;
}

class SalesInvoiceDto {
  const SalesInvoiceDto({
    required this.invoiceNumber,
    required this.customerId,
    required this.invoiceDate,
    required this.dueDate,
    required this.status,
    required this.totalAmount,
    required this.balanceDue,
    required this.incomeAccountId,
    required this.arAccountId,
    this.id,
    this.description,
    this.qrCodeData,
  });
  final String? id;
  final String invoiceNumber;
  final String customerId;
  final String invoiceDate;
  final String dueDate;
  final String status;
  final String totalAmount;
  final String balanceDue;
  final String? description;
  final String incomeAccountId;
  final String arAccountId;
  final String? qrCodeData;

  @override
  int get hashCode =>
      id.hashCode ^
      invoiceNumber.hashCode ^
      customerId.hashCode ^
      invoiceDate.hashCode ^
      dueDate.hashCode ^
      status.hashCode ^
      totalAmount.hashCode ^
      balanceDue.hashCode ^
      description.hashCode ^
      incomeAccountId.hashCode ^
      arAccountId.hashCode ^
      qrCodeData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SalesInvoiceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          invoiceNumber == other.invoiceNumber &&
          customerId == other.customerId &&
          invoiceDate == other.invoiceDate &&
          dueDate == other.dueDate &&
          status == other.status &&
          totalAmount == other.totalAmount &&
          balanceDue == other.balanceDue &&
          description == other.description &&
          incomeAccountId == other.incomeAccountId &&
          arAccountId == other.arAccountId &&
          qrCodeData == other.qrCodeData;
}

class SalesInvoiceLineDto {
  const SalesInvoiceLineDto({
    required this.description,
    required this.quantity,
    required this.unitPrice,
    required this.taxAmount,
    this.productId,
  });
  final String? productId;
  final String description;
  final String quantity;
  final String unitPrice;
  final String taxAmount;

  @override
  int get hashCode =>
      productId.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unitPrice.hashCode ^
      taxAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SalesInvoiceLineDto &&
          runtimeType == other.runtimeType &&
          productId == other.productId &&
          description == other.description &&
          quantity == other.quantity &&
          unitPrice == other.unitPrice &&
          taxAmount == other.taxAmount;
}
