// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

Future<(String, String)> generateZatcaKeyPair() =>
    RustLib.instance.api.crateApiZatcaGenerateZatcaKeyPair();

Future<String> generateZatcaCsr(
        {required ZatcaCsrInputDto input, required String keyPairPem}) =>
    RustLib.instance.api
        .crateApiZatcaGenerateZatcaCsr(input: input, keyPairPem: <credential-fixture>);

Future<(String, String)> generateZatcaSignedXml(
        {required ZatcaInvoiceInputDto input,
        required String certificatePem,
        required String privateKeyPem}) =>
    RustLib.instance.api.crateApiZatcaGenerateZatcaSignedXml(
        input: input,
        certificatePem: certificatePem,
        privateKeyPem: <credential-fixture>);

class ZatcaCsrInputDto {
  final String commonName;
  final String organizationUnit;
  final String organization;
  final String country;
  final String serialNumber;
  final String vatNumber;
  final String businessCategory;
  final String registeredAddress;

  const ZatcaCsrInputDto({
    required this.commonName,
    required this.organizationUnit,
    required this.organization,
    required this.country,
    required this.serialNumber,
    required this.vatNumber,
    required this.businessCategory,
    required this.registeredAddress,
  });

  @override
  int get hashCode =>
      commonName.hashCode ^
      organizationUnit.hashCode ^
      organization.hashCode ^
      country.hashCode ^
      serialNumber.hashCode ^
      vatNumber.hashCode ^
      businessCategory.hashCode ^
      registeredAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZatcaCsrInputDto &&
          runtimeType == other.runtimeType &&
          commonName == other.commonName &&
          organizationUnit == other.organizationUnit &&
          organization == other.organization &&
          country == other.country &&
          serialNumber == other.serialNumber &&
          vatNumber == other.vatNumber &&
          businessCategory == other.businessCategory &&
          registeredAddress == other.registeredAddress;
}

class ZatcaInvoiceInputDto {
  final String id;
  final String uuid;
  final String issueDate;
  final String issueTime;
  final String invoiceTypeCode;
  final BigInt invoiceCounterValue;
  final String previousInvoiceHash;
  final ZatcaPartyDto sellerParty;
  final ZatcaPartyDto buyerParty;
  final List<ZatcaInvoiceLineDto> lines;

  const ZatcaInvoiceInputDto({
    required this.id,
    required this.uuid,
    required this.issueDate,
    required this.issueTime,
    required this.invoiceTypeCode,
    required this.invoiceCounterValue,
    required this.previousInvoiceHash,
    required this.sellerParty,
    required this.buyerParty,
    required this.lines,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      issueDate.hashCode ^
      issueTime.hashCode ^
      invoiceTypeCode.hashCode ^
      invoiceCounterValue.hashCode ^
      previousInvoiceHash.hashCode ^
      sellerParty.hashCode ^
      buyerParty.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZatcaInvoiceInputDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          issueDate == other.issueDate &&
          issueTime == other.issueTime &&
          invoiceTypeCode == other.invoiceTypeCode &&
          invoiceCounterValue == other.invoiceCounterValue &&
          previousInvoiceHash == other.previousInvoiceHash &&
          sellerParty == other.sellerParty &&
          buyerParty == other.buyerParty &&
          lines == other.lines;
}

class ZatcaInvoiceLineDto {
  final String id;
  final String quantity;
  final String unitPrice;
  final String taxCategory;
  final String itemName;

  const ZatcaInvoiceLineDto({
    required this.id,
    required this.quantity,
    required this.unitPrice,
    required this.taxCategory,
    required this.itemName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      quantity.hashCode ^
      unitPrice.hashCode ^
      taxCategory.hashCode ^
      itemName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZatcaInvoiceLineDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          quantity == other.quantity &&
          unitPrice == other.unitPrice &&
          taxCategory == other.taxCategory &&
          itemName == other.itemName;
}

class ZatcaPartyDto {
  final String partyId;
  final String partyIdScheme;

  const ZatcaPartyDto({
    required this.partyId,
    required this.partyIdScheme,
  });

  @override
  int get hashCode => partyId.hashCode ^ partyIdScheme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZatcaPartyDto &&
          runtimeType == other.runtimeType &&
          partyId == other.partyId &&
          partyIdScheme == other.partyIdScheme;
}
